
exec-once = vb-cmd-refresh-dunst
exec-once = vb-util-lockscreen-cache

# Source: Omarchy
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
