dwindle {
	force_split = 2
	preserve_split = true
	special_scale_factor = 0.98
}

misc {
	disable_hyprland_logo = true
    # We're doing it in uwsm env sciprt
	disable_xdg_env_checks = true
    disable_watchdog_warning = true
	disable_splash_rendering = true
	disable_hyprland_guiutils_check = true

	col.splash = $background
	background_color = $background

	allow_session_lock_restore = true

	# new_window_takes_over_fullscreen = 2
	enable_anr_dialog = true

    font_family = Cascadia Code

    vfr = true
    vrr = 2
}

binds {
	hide_special_on_workspace_change = true
	scroll_event_delay = 0
}

ecosystem {
	no_update_news = true
	enforce_permissions = true
}

render {
    cm_auto_hdr = 0
    send_content_type = false
    cm_enabled = false
}

general {
    resize_on_border = true
    allow_tearing = true
}
