### Load default Vibranium settings.

# Important scripts that must start with the compositor.
source = ~/.local/share/vibranium/default/hypr/autostart.conf

# General defaults.
source = ~/.local/share/vibranium/default/hypr/general.conf

# Basic appearance. Colors defined here may be overridden
# by the theme file. If the theme does not define them,
# values here are used as fallback.
source = ~/.local/share/vibranium/default/hypr/look-and-feel.conf

# Theme file.
# Keep this order exactly as is — it matters.
# The theme file must be loaded before window rules,
# because window-rules.conf relies on special color variables.
# If loaded after, those variables won’t apply
# and fallback colors will be used instead.
source = ~/.config/vibranium/current/theme/hyprland.conf

# Window / Layer rules.
source = ~/.local/share/vibranium/default/hypr/layer-rules.conf
source = ~/.local/share/vibranium/default/hypr/window-rules.conf

# https://wiki.hypr.land/Configuring/Permissions/
source = ~/.local/share/vibranium/default/hypr/persmissions.conf

# Default binds.
source = ~/.local/share/vibranium/default/hypr/binds.conf

# Default input options like gestures, keyboard repeat rate,
source = ~/.local/share/vibranium/default/hypr/input.conf
