$attention = rgb(ff0000)

# Fallback
$activeBorderColor = rgb(255,255,255)
$inactiveBorderColor = rgba(255,255,255,0.5)

general {
	gaps_in = 5
	gaps_out = 7
	border_size = 2

  col.active_border = $activeBorderColor
  col.inactive_border = $inactiveBorderColor
}

decoration {
	rounding = 0

	dim_inactive = true
	dim_strength = 0.1
	dim_special = 0.4
	dim_around = 0.4
  dim_modal = true

	border_part_of_window = false

	blur {
		enabled = false
		xray = true

		passes = 3
		size = 3
	}

	shadow {
		enabled = true
    color = rgba(17171770)
		render_power = 0
		range = 5
	}
}

animations:enabled = true
