general {
	gaps_in = 5
	gaps_out = 7
	border_size = 2

	col.active_border = $accent
	col.inactive_border = $muted
}

decoration {
	rounding = 0

	dim_inactive = true
	dim_strength = 0.1
	dim_special = 0.4
	dim_around = 0.4
    dim_modal = true

	border_part_of_window = false

	blur {
		enabled = false
		xray = true

		passes = 3
		size = 3
	}

	shadow {
		enabled = true
    color = rgba(00000070)
		render_power = 0
		range = 5
	}
}

animations:enabled = true
