
windowrule = tag +gameWindow, match:class (?i)(osu!|gamescope|cs(2|go_linux)|steam(_(app(_\d+)?)
windowrule = tag +gameWindow, match:class ^()$, match:title ^Minecraft\*\s\d\.\d?$

windowrule = tag +gameLauncher, match:class [\w.]*?(steam|heroic|lutris|prismlauncher|.*\.RetroArch|dolphin-emu)

# Credits: Omarchy
windowrule = tag +chromiumBasedBrowser, match:class ((google-)?chrom(e|ium)|brave-browser|microsoft-edge|vivaldi-stable|helium)
windowrule = tag +firefoxBasedBrowser, match:class (?i)(frefox|zen|librewolf)

windowrule = tag +browserWindow, match:tag chromiumBasedBrowser
windowrule = tag +browserWindow, match:tag firefoxBasedBrowser
windowrule = tag +browserWindow, match:class org\.qutebrowser\.qutebrowser

windowrule = tag +officeWindow, match:class [\w.]*?(only|libre|s)office(?:-\w+)*

# Some Omarchy themes may apply not only Hyprland colors, but also their
# own settings. By default, Omarchy applies an opacity rule of 0.97 to all
# windows, using a special tag, and disables opacity for windows with
# specific titles. Vibranium does not include such a rule by default, but
# it is better to be prepared for these cases.
windowrule = opaque on, match:title .* - YouTube - .*

# Some applications benefit from automatically regaining focus after certain actions.
# For example, when logging in through a browser, the original app window can take
# focus again once the login is complete. This approach has worked well over time.
windowrule = tag +focusOnActivate, match:class (discord|vesktop|spotify)
windowrule = tag +focusOnActivate, match:tag browserWindow

windowrule = match:tag focusOnActivate, focus_on_activate true

# Make game windows opaque, allow tearing (fullscreen only).
windowrule = match:tag gameWindow, immediate true
windowrule = match:tag gameWindow, opaque true

# Also fix Steam's login window that appears almost over the screen.
windowrule = match:class [Ss]team, match:title Sign in to Steam, center true

# Special rules for floating terminal window.
windowrule = match:class org\.vb\.term\.float, float true
windowrule = match:class org\.vb\.term\.float, center true
windowrule = match:class org\.vb\.term\.float, size monitor_w*0.7 monitor_h*0.7

# Matches window titles that likely indicate attention-demanding dialogs
# (e.g. confirmations, warnings, permissions, save prompts, errors).
# Used to apply visual emphasis so these windows are harder to miss.
$warn_actions = (open shell script|empty trash|authenticate|confirm|trash|delete)
$warn_states  = (warning|attention|alert|error)
$warn_misc    = (permission|quit|requ(ired|est))
$warn_save    = save[\s\w]*\?

$warn_actions_classes = (Pinentry-gtk)

$warn_titles = (?i)($warn_actions|$warn_states|$warn_misc|$warn_save)([\s\w]*)?\??
$warn_classes = (?i)($warn_actions_titles)([\s\w]*)?\??

windowrule = match:title $warn_titles, border_color $attention, dim_around true
windowrule = match:class $warn_actions_classes, border_color $attention, dim_around true

# Thunar special rules.
# Keeps small contextual windows always visible and focused.
# To revert, just tile the window.
windowrule {
  name = File Operation Progress

  match:float = true
  match:class = [Tt]hunar
  match:title = ^(Rename \"(.*?)\"|Create New Folder|File Operation Progress)$

  float = true
  center = true
  dim_around = true
}

# Special rules for Vibranium utilities, running in a floating terminal window
windowrule {
  name = Floating Terminal (dimmed)
  match:class = org\.vb\.term\.float

  # All package management scripts
  # And pretty much every TUI that can be launched by clicking on a Waybar module.
  match:title = (vb-(tui|webapp|update|pkg|setup|env|theme-install).*|bluetui|vb-update|wiremix|nmtui|impala|iwctl|pass)
  match:float = true

  size = monitor_w*0.7 monitor_h*0.7
  center = true
  dim_around = true
  stay_focused = true
}
