theme[main_bg]="#0f0f0f"
theme[main_fg]="#b6aa94"
theme[title]="#ded4c4"
theme[hi_fg]="#cc4400"

theme[selected_bg]="#333333"
theme[selected_fg]="#cc4400"
theme[inactive_fg]="#484848"
theme[proc_misc]="#cc4400"

theme[cpu_box]="#484848"
theme[mem_box]="#484848"
theme[net_box]="#484848"
theme[proc_box]="#484848"
theme[div_line]="#484848"

theme[temp_start]="#627648"
theme[temp_mid]="#cc4400"
theme[temp_end]="#9a3c29"

theme[cpu_start]="#ffaa00"
theme[cpu_mid]="#cc4400"
theme[cpu_end]="#9a3c29"

theme[free_start]="#cc4400"
theme[free_mid]="#627648"
theme[free_end]="#627648"

theme[cached_start]="#cc4400"
theme[cached_mid]="#627648"
theme[cached_end]="#627648"

theme[available_start]="#cc4400"
theme[available_mid]="#627648"
theme[available_end]="#627648"

theme[used_start]="#cc4400"
theme[used_mid]="#627648"
theme[used_end]="#627648"

theme[download_start]="#405ca5"
theme[download_mid]="#cc4400"
theme[download_end]="#9a3c29"

theme[upload_start]="#405ca5"
theme[upload_mid]="#cc4400"
theme[upload_end]="#9a3c29"
