# vim:ft=systemd
# man zram-generator.conf:
#
# A piecewise-linear size 1:1 for the first 4G, then 1:2 above, up to a max of 32G:
#      zram device size
#          ^
#      32G>|                                                oooooooooooooo
#          |                                            o
#      30G>|                                        o
#          |
#         /=/
#          |
#       8G>│                           o
#          │                       o
#          │                   o
#          │               o
#          │           o
#       4G>│       o
#          │     o
#          │   o
#       1G>│ o
#          0───────────────────────────────────||──────────────────────> total usable RAM
#            ^     ^       ^               ^        ^       ^       ^
#            1G    4G      8G             12G      56G     60G     64G

[zram0]
zram-size = min(min(ram, 4096) + max(ram - 4096, 0) / 2, 32 * 1024)
compression-algorithm = lzo-rle zstd(level=3) (type=idle)
