[colors.primary]
background = "#111c18"
foreground = "#d2d3c0"
dim_foreground = "#0d1713"
bright_foreground = "#e4e5d1"

[colors.cursor]
text   = "#111c18"
cursor = "#afb0a0"

[colors.vi_mode_cursor]
text   = "#e4e5d1"
cursor = "#57a5e5"

[colors.search.matches]
background = "#263c33"
foreground = "#d2d3c0"

[colors.hints.start]
background = "#263c33"
foreground = "#d2d3c0"

[colors.hints.end]
background = "#263c33"
foreground = "#d2d3c0"

[colors.line_indicator]
background = "#263c33"
foreground = "#d2d3c0"

[colors.footer_bar]
background = "#263c33"
foreground = "#d2d3c0"

[colors.selection]
background = "#374c43"
foreground = "#e4e5d1"

[colors.normal]
black   = "#455f53"
red     = "#e75a7c"
green   = "#8fb573"
yellow  = "#dbb651"
blue    = "#57a5e5"
magenta = "#aaaaff"
cyan    = "#70c2be"
white   = "#d1d2c3"

[colors.bright]
black   = "#58796b"
red     = "#ef7b93"
green   = "#a3c28c"
yellow  = "#e2c476"
blue    = "#78b6eb"
magenta = "#b9baff"
cyan    = "#8ccdca"
white   = "#e9ead9"

[colors.dim]
black   = "#131e1a"
red     = "#b1435d"
green   = "#6c8a56"
yellow  = "#a78b3c"
blue    = "#417daf"
magenta = "#8181c3"
cyan    = "#549491"
white   = "#babbae"

