black_dim = "#131e1a"
black = "#19231f"
black_bright = "#1e2925"

red_dim = "#b1435d"
red = "#e75a7c"
red_bright = "#ef7b93"

pink_dim = "#b3658b"
pink = "#df7cad"
pink_bright = "#eaa0c3"

green_dim = "#6c8a56"
green = "#8fb573"
green_bright = "#a3c28c"

yellow_dim = "#a78b3c"
yellow = "#dbb651"
yellow_bright = "#e2c476"

orange_dim = "#c3744c"
orange = "#ff9966"
orange_bright = "#ffac83"

blue_dim = "#417daf"
blue = "#57a5e5"
blue_bright = "#78b6eb"

purple_dim = "#8181c3"
purple = "#aaaaff"
purple_bright = "#b9baff"

cyan_dim = "#549491"
cyan = "#70c2be"
cyan_bright = "#8ccdca"

white_dim = "#babbae"
white = "#d1d2c3"
white_bright = "#e9ead9"

gray_dim = "#35493f"
gray = "#3d5449"
gray_bright = "#4d6258"

accent_dim = "#549491"
accent = "#70c2be"
accent_bright = "#8ccdca"

background_h = "#0d1713"
background_0 = "#111c18"
background_1 = "#1d2f28"
background_2 = "#263c33"
background_3 = "#374c43"
background_4 = "#455f53"
background_5 = "#58796b"

foreground_h = "#edf1ef"
foreground_0 = "#d3dcd8"
foreground_1 = "#bac7c1"
foreground_2 = "#a0b3ab"
foreground_3 = "#889f95"
foreground_4 = "#708c80"
