theme[main_bg]="#192330"
theme[main_fg]="#f3f4ec"
theme[title]="#f3f4ec"
theme[hi_fg]="#f57f82"

theme[selected_bg]="#374553"
theme[selected_fg]="#eebf77"

theme[inactive_fg]="#374553"
theme[graph_text]="#475f6b"

theme[proc_misc]="#475f6b"
theme[cpu_box]="#475f6b"
theme[mem_box]="#475f6b"
theme[net_box]="#475f6b"
theme[proc_box]="#475f6b"
theme[div_line]="#475f6b"

theme[temp_start]="#b3d491"
theme[temp_mid]="#eebf77"
theme[temp_end]="#f57f82"

theme[cpu_start]="#b3d491"
theme[cpu_mid]="#eebf77"
theme[cpu_end]="#f57f82"

theme[free_start]="#f57f82"
theme[free_mid]="#eebf77"
theme[free_end]="#b3d491"

theme[cached_start]="#f57f82"
theme[cached_mid]="#f7916e"
theme[cached_end]="#b3d491"

theme[available_start]="#f57f82"
theme[available_mid]="#f7916e"
theme[available_end]="#b3d491"

theme[used_start]="#f57f82"
theme[used_mid]="#f7916e"
theme[used_end]="#b3d491"

theme[download_start]="#475f6b"
theme[download_mid]="#f7916e"
theme[download_end]="#f57f82"

theme[upload_start]="#475f6b"
theme[upload_mid]="#f7916e"
theme[upload_end]="#f57f82"

theme[process_start]="#b3d491"
theme[process_mid]="#f7916e"
theme[process_end]="#f57f82"
