theme[main_bg]="#192330"
theme[main_fg]="#f8f9e8"
theme[title]="#f8f9e8"
theme[hi_fg]="#f57f82"

theme[selected_bg]="#29394f"
theme[selected_fg]="#f5d098"

theme[inactive_fg]="#374145"
theme[graph_text]="#4a585c"

theme[proc_misc]="#698081"
theme[cpu_box]="#4a585c"
theme[mem_box]="#4a585c"
theme[net_box]="#4a585c"
theme[proc_box]="#4a585c"
theme[div_line]="#4a585c"

theme[temp_start]="#698081"
theme[temp_mid]="#f5d098"
theme[temp_end]="#f57f82"

theme[cpu_start]="#698081"
theme[cpu_mid]="#f5d098"
theme[cpu_end]="#f57f82"

theme[free_start]="#f57f82"
theme[free_mid]="#f5d098"
theme[free_end]="#698081"

theme[cached_start]="#698081"
theme[cached_mid]="#f4a261"
theme[cached_end]="#f57f82"

theme[available_start]="#698081"
theme[available_mid]="#f4a261"
theme[available_end]="#f57f82"

theme[used_start]="#698081"
theme[used_mid]="#f4a261"
theme[used_end]="#f57f82"

theme[download_start]="#698081"
theme[download_mid]="#f4a261"
theme[download_end]="#f57f82"

theme[upload_start]="#698081"
theme[upload_mid]="#f4a261"
theme[upload_end]="#f57f82"

theme[process_start]="#CBE3B3"
theme[process_mid]="#f4a261"
theme[process_end]="#f57f82"
