black_dim = "#323d43"
black = "#374553"
black_bright = "#475f6b"

red_dim = "#f24f55"
red = "#f57f82"
red_bright = "#f9afb1"

pink_dim = "#e764c9"
pink = "#ed92d7"
pink_bright = "#f4bee7"

green_dim = "#a0c969"
green = "#b3d491"
green_bright = "#cfe3b5"

yellow_dim = "#e5a94d"
yellow = "#eebf77"
yellow_bright = "#f3d5a5"

orange_dim = "#f26840"
orange = "#f7916e"
orange_bright = "#fab49e"

blue_dim = "#5a8fd8"
blue = "#84aae1"
blue_bright = "#adc6eb"

purple_dim = "#8f54de"
purple = "#a87ce9"
purple_bright = "#c6a8f0"

cyan_dim = "#68cab7"
cyan = "#8dd8cb"
cyan_bright = "#b4e4da"

white_dim = "#c6c7a9"
white = "#f8f9e8"
white_bright = "#f9faec"

gray_dim = "#576b75"
gray = "#6c8993"
gray_bright = "#8ba0a7"

accent_dim = "#39ac95"
accent = "#57c1b0"
accent_bright = "#7bd1c0"

background_h = "#171c1f"
background_0 = "#1c2225"
background_1 = "#232a2e"
background_2 = "#323d43"
background_3 = "#374553"
background_4 = "#3d525c"
background_5 = "#475f6b"

foreground_h = "#eef7f7"
foreground_0 = "#dcefef"
foreground_1 = "#cbe7e7"
foreground_2 = "#b9dfdf"
foreground_3 = "#a8d7d7"
foreground_4 = "#96cfcf"
