black_dim = "#20212a"
black = "#25262f"
black_bright = "#2b2c35"

red_dim = "#9f3234"
red = "#c34043"
red_bright = "#e82424"

pink_dim = "#c96484"
pink = "#d27e99"
pink_bright = "#e1a7ba"

green_dim = "#617a57"
green = "#76946a"
green_bright = "#98bb6c"

yellow_dim = "#b18e4e"
yellow = "#c0a36e"
yellow_bright = "#e6c384"

orange_dim = "#ff7e2e"
orange = "#ffa066"
orange_bright = "#ffb78a"

blue_dim = "#5e84cf"
blue = "#7e9cd8"
blue_bright = "#7fb4ca"

purple_dim = "#775ba4"
purple = "#957fb8"
purple_bright = "#938aa9"

cyan_dim = "#577a70"
cyan = "#6a9589"
cyan_bright = "#7aa89f"

white_dim = "#c0b993"
white = "#dcd7ba"
white_bright = "#f2ecbc"

gray_dim = "#55544e"
gray = "#727169"
gray_bright = "#85837a"

blue_dim = "#5e84cf"
blue = "#7e9cd8"
blue_bright = "#7fb4ca"

accent_dim = "#577a70"
accent = "#6a9589"
accent_bright = "#7aa89f"

background_h = "#16161d"
background_0 = "#1e1f28"
background_1 = "#2a2a37"
background_2 = "#363646"
background_3 = "#54546d"
background_4 = "#626279"
background_5 = "#717086"

foreground_h = "#e7e4d0"
foreground_0 = "#dcd7ba"
foreground_1 = "#c6c1a7"
foreground_2 = "#b0ab95"
foreground_3 = "#9b9783"
foreground_4 = "#868372"
