
animations {
	bezier = easeOutQuint,  0.15, 1.15, 0.32, 1.0
    bezier = almostLinear,  0.50, 0.50, 0.75, 1.0
    bezier = linear,        0.00, 0.00, 1.00, 1.0

    bezier = WindowsIn,     0.20, 1.17, 0.15, 1.00
	bezier = screenZoom,    0.50, 1.35, 0.32, 1.00
	bezier = WindowsMove,   0.35, 1.11, 0.35, 1.01
	bezier = notifications, 0.20, 1.30, 0.65, 1.00

	#           What          on|off  speed bezier name  opts
    animation = border,        false,    5.0, easeOutQuint
	animation = fade,          true,    1.0, almostLinear

	animation = border,        true,    0.7, linear
	animation = fadeDim,       true,    0.7, linear
	animation = fadeSwitch,    true,    0.7, linear
	animation = fadeShadow,    true,    0.7, linear

    animation = layers,        true,    3.0, notifications
    animation = fadeLayersIn,  true,    3.0, default
    animation = fadeLayersOut, true,    3.0, default

	animation = workspaces,   false

    animation = windowsIn,     true,    3.8, WindowsIn, gnomed
	animation = windowsOut,    true,    5.0, easeOutQuint, gnomed
	animation = windowsMove,   true,    4.0, WindowsMove, slide

	animation = zoomFactor, true, 2.5, screenZoom

}
