black_dim = "#26233a"
black = "#302c49"
black_bright = "#433d66"

red_dim = "#bc5b76"
red = "#eb6f92"
red_bright = "#f18ba5"

pink_dim = "#9d86b9"
pink = "#c4a7e7"
pink_bright = "#cfb7ec"

green_dim = "#2b5e73"
green = "#31748f"
green_bright = "#5b8ca3"

yellow_dim = "#c59b61"
yellow = "#f6c177"
yellow_bright = "#f9cc90"

orange_dim = "#bb7c7a"
orange = "#ea9a97"
orange_bright = "#efaca9"

blue_dim = "#bc9795"
blue = "#ebbcba"
blue_bright = "#efc8c6"

purple_dim = "#9d86b9"
purple = "#c4a7e7"
purple_bright = "#cfb7ec"

cyan_dim = "#7ea6ad"
cyan = "#9ccfd8"
cyan_bright = "#afd8df"

white_dim = "#a9a8b6"
white = "#c9c8db"
white_bright = "#e0def4"

gray_dim = "#433f56"
gray = "#514c6a"
gray_bright = "#6e6a83"

accent_dim = "#bc9795"
accent = "#ebbcba"
accent_bright = "#efc8c6"

background_h = "#0b0a10"
background_0 = "#191724"
background_1 = "#1f1d2e"
background_2 = "#26233a"
background_3 = "#302c49"
background_4 = "#433d66"
background_5 = "#554e83"

foreground_h = "#e0def4"
foreground_0 = "#c9c8db"
foreground_1 = "#a9a8b6"
foreground_2 = "#908caa"
foreground_3 = "#6e6a86"
foreground_4 = "#605c75"
