black_dim = "#0b0d0e"
black = "#1e2326"
black_bright = "#374145"

red_dim = "#493b40"
red = "#e57e80"
red_bright = "#eb9e9f"

pink_dim = "#571e39"
pink = "#db97b7"
pink_bright = "#e6b3ca"

green_dim = "#3c4841"
green = "#a7c080"
green_bright = "#c9d8b0"

yellow_dim = "#45443c"
yellow = "#dabc7f"
yellow_bright = "#e5cfa4"

orange_dim = "#632c13"
orange = "#e59875"
orange_bright = "#ecb69c"

blue_dim = "#384b55"
blue = "#7fbbb3"
blue_bright = "#b2d7d2"

purple_dim = "#463f48"
purple = "#d699b6"
purple_bright = "#deabc4"

cyan_dim = "#274e31"
cyan = "#83c092"
cyan_bright = "#92c8a0"

white_dim = "#4d4228"
white = "#d3c6aa"
white_bright = "#dbd0b9"

gray_dim = "#7a8478"
gray = "#859289"
gray_bright = "#9da9a0"

accent_dim = "#3c4841"
accent = "#a7c080"
accent_bright = "#c9d8b0"

background_h = "#1e2326"
background_0 = "#272e33"
background_1 = "#32393d"
background_2 = "#3d4448"
background_3 = "#494f53"
background_4 = "#555a5f"
background_5 = "#61666a"

foreground_h = "#dbd0b9"
foreground_0 = "#d3c6aa"
foreground_1 = "#c8b793"
foreground_2 = "#b9a374"
foreground_3 = "#a79369"
foreground_4 = "#97855f"
foreground_5 = "#817151"
