[colors.primary]
background = "#fbf1c7"
foreground = "#3c3836"
dim_foreground    = "#7c6f64"
bright_foreground = "#282828"

[colors.cursor]
text   = "#fbf1c7"
cursor = "#928374"

[colors.vi_mode_cursor]
text   = "#f9f5d7"
cursor = "#98971a"

[colors.search.matches]
background = "#d5c4a1"
foreground = "#d79921"

[colors.hints.start]
background = "#d79921"
foreground = "#d5c4a1"

[colors.hints.end]
background = "#cc241d"
foreground = "#282828"

[colors.line_indicator]
background = "#d5c4a1"
foreground = "#d79921"

[colors.footer_bar]
background = "#d5c4a1"
foreground = "#d79921"

[colors.selection]
background = "#a89984"
foreground = "#f9f5d7"

[colors.normal]
black   = "#928374"
red     = "#9d0006"
green   = "#79740e"
yellow  = "#b57614"
blue    = "#076678"
magenta = "#8f3f71"
cyan    = "#427b58"
white   = "#3c3836"

[colors.bright]
black   = "#a89984"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#504945"

[colors.dim]
black   = "#7c6f64"
red     = "#ad5858"
green   = "#6f8352"
yellow  = "#a86b2c"
blue    = "#043943"
magenta = "#713259"
cyan    = "#396A4C"
white   = "#3c3836"
