black_dim = "#f9f5d7"
black = "#ebdbb2"
black_bright = "#bdae93"

red_dim = "#9d0006"
red = "#cc241d"
red_bright = "#e54d48"

pink_dim = "#8c4565"
pink = "#ba7393"
pink_bright = "#c992ab"

green_dim = "#79740e"
green = "#98971a"
green_bright = "#b3b31e"

yellow_dim = "#b57614"
yellow = "#d79921"
yellow_bright = "#e3b04a"

orange_dim = "#af3a03"
orange = "#d65d0e"
orange_bright = "#f0690f"

blue_dim = "#076678"
blue = "#458588"
blue_bright = "#55a5aa"

purple_dim = "#8f3f71"
purple = "#b16286"
purple_bright = "#ba7393"

cyan_dim = "#427b58"
cyan = "#689d6a"
cyan_bright = "#80ac82"

white_dim = "#f9f5d7"
white = "#fbf1c7"
white_bright = "#ebdbb2"

gray_dim = "#7c6f64"
gray = "#928374"
gray_bright = "#a3968a"

accent_dim = "#b57614"
accent = "#d79921"
accent_bright = "#e3b04a"

background_h = "#f9f5d7"
background_0 = "#fbf1c7"
background_1 = "#ebdbb2"
background_2 = "#d5c4a1"
background_3 = "#bdae93"
background_4 = "#a89984"
background_5 = "#928374"

foreground_h = "#1d2021"
foreground_0 = "#282828"
foreground_1 = "#3c3836"
foreground_2 = "#3c3836"
foreground_3 = "#504945"
foreground_4 = "#665c54"
