black_dim = "#e5d3c3"
black = "#ebded2"
black_bright = "#f2e9e1"

red_dim = "#915163"
red = "#b4637a"
red_bright = "#c37f91"

pink_dim = "#886384"
pink = "#a97aa4"
pink_bright = "#b991b4"

green_dim = "#24556a"
green = "#286983"
green_bright = "#548399"

yellow_dim = "#bb7e2d"
yellow = "#ea9d34"
yellow_bright = "#f1ae5c"

orange_dim = "#b97519"
orange = "#e79118"
orange_bright = "#f0a54b"

blue_dim = "#ac6966"
blue = "#d7827e"
blue_bright = "#e09994"

purple_dim = "#746388"
purple = "#907aa9"
purple_bright = "#a491b8"

cyan_dim = "#477780"
cyan = "#56949f"
cyan_bright = "#76a7b0"

white_dim = "#6b6594"
white = "#827ca6"
white_bright = "#9a95b7"

gray_dim = "#827c92"
gray = "#9893a5"
gray_bright = "#ada9b8"

accent_dim = "#477780"
accent = "#56949f"
accent_bright = "#76a7b0"

background_h = "#fbf7f2"
background_0 = "#faf4ed"
background_1 = "#f2e9e1"
background_2 = "#e7e3e2"
background_3 = "#dfdad9"
background_4 = "#cecacd"
background_5 = "#beb8bc"

foreground_h = "#433f5c"
foreground_0 = "#464261"
foreground_1 = "#59547b"
foreground_2 = "#6b6594"
foreground_3 = "#827ca6"
foreground_4 = "#9a95b7"
