[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
dim_foreground    = "#a89984"
bright_foreground = "#fbf1c7"

[colors.cursor]
text   = "#282828"
cursor = "#ebdbb2"

[colors.vi_mode_cursor]
text   = "#ebdbb2"
cursor = "#8ec07c"

[colors.search.matches]
background = "#504945"
foreground = "#d79921"

[colors.hints.start]
background = "#d79921"
foreground = "#fbf1c7"

[colors.hints.end]
background = "#cc241d"
foreground = "#282828"

[colors.line_indicator]
background = "#504945"
foreground = "#d79921"

[colors.footer_bar]
background = "#504945"
foreground = "#d79921"

[colors.selection]
background = "#504945"
foreground = "#fbf1c7"

[colors.normal]
black   = "#3c3836"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#d5c4a1"

[colors.bright]
black   = "#665c54"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.dim]
black   = "#1d2021"
red     = "#442e2d"
green   = "#333e34"
yellow  = "#463c29"
blue    = "#2e3b3b"
magenta = "#3c333b"
cyan    = "#2E472F"
white   = "#a89984"
