# Apply Vibranium settings. Do not remove nor edit this line!
source = ~/.local/share/vibranium/default/hypr/init.conf

# Your overrides below.
# Everything below this line is for your customizations.
# Define new options here or override existing defaults.
# You can use this file, but using the hyprland.conf.d
# directory is recommended for a more structured setup.
# Files in that directory include detailed syntax explanations
# and examples. If you're not familiar with Hyprland config,
# it’s worth checking them out.

# Automatically source all *.conf files from this sub directory.
source = ./hyprland.conf.d/*.conf
