# Default Hyprlock configuration for Vibranium
# Full documentation: https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

source = ../vibranium/current/theme/hyprlock.conf

general {
  # Self-explanatory
  ignore_empty_input = true
  # Start rendering the lockscreen without waiting for
  # the wallpaper to load. Lockscreen appears instantly,
  # but the background will be black for some time until
  # it is ready.
  immediate_render = false

  # Completely hide the cursor.
  hide_cursor = true

  # 0 - disabled, 1 - enabled, 2 - auto
  fractional_scaling = 1
}

background {
    # Keep empty so the lockscreen is shown on all monitors.
    monitor =

    # Regular text color variable. Defined in the theme
    # file sourced above. It's not recommended to change it,
    # since it dynamically sets the text color per theme.
    color = $color

    # How many blur passes to process.
    # The higher the value, the higher the GPU load.
    # Feel free to change.
    blur_passes = 3

    # The path to the current wallpaper.
    # This file is actually a symlink that updates
    # externally when you change the wallpaper.
    path = ~/.config/vibranium/current/background

    # You can render the lockscreen over the contents of
    # your screen by using the 'screenshot' keyword.
    # Comment out the line above and uncomment this one
    # to see the effect.
    # path = screenshot
}

# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/#input-field
input-field {
    # Keep empty so the lockscreen is shown on all monitors.
    monitor =

    # Input box size.
    size = 325, 45

    # Self-explanatory
    position = 0, 0
    halign = center
    valign = center

    # Same as with $color, these are defined by the
    # theme file. If you change them once, the lockscreen
    # will have the same colors no matter the active theme.
    inner_color = $inner_color
    outer_color = $outer_color

    # Input box outline.
    outline_thickness = 2

    font_family = Cascadia Code

    # You get the point.
    font_color = $font_color

    placeholder_text = Enter Password

    # You get the point.
    check_color = $check_color

    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    # Input box corner radius.
    rounding = 0

    # Don't hide the input box when there's no input.
    fade_on_empty = false
}

animations {
  enabled = true

  # https://wiki.hypr.land/Configuring/Animations
  bezier = curve, 0.23, 1.0, 0.32, 1.0

  animation = fadeIn,  true, 1.0, curve
  animation = fadeOut, true, 0.5, curve
}
