# WARNING: This file is read only! Under no circumstances should you delete or edit this file!
# If you want to edit hyprland's configuration, consider editing existing
# files in the hyprland.conf.d subfolder, or create there a new one.
# New files will be sources automatically.

# Load current theme. It MUST be the first line
source = ../vibranium/theme/current/hyprland.conf
#        ^
# The path is relative to (this) file

# Load defaults
source = ~/.local/share/vibranium/default/hypr/autostart.conf
source = ~/.local/share/vibranium/default/hypr/general.conf
source = ~/.local/share/vibranium/default/hypr/layer-rules.conf
source = ~/.local/share/vibranium/default/hypr/look-and-feel.conf
source = ~/.local/share/vibranium/default/hypr/window-rules.conf
source = ~/.local/share/vibranium/default/hypr/persmissions.conf
source = ~/.local/share/vibranium/default/hypr/binds.conf
source = ~/.local/share/vibranium/default/hypr/input.conf

# Load user's overrides
# The folder hyprland.conf.d already has template files for binds, monitors, input, and more.
# All new files should be created in this directory. They are sourced immediately, no setup needed.
source = ./hyprland.conf.d/*.conf
