[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"
dim_foreground    = "#9aa5ce"
bright_foreground = "#d1d8f8"

[colors.cursor]
text   = "#1a1b26"
cursor = "#c0caf5"

[colors.vi_mode_cursor]
text   = "#1a1b26"
cursor = "#7aa2f7"

[colors.search.matches]
background = "#303146"
foreground = "#d1d8f8"

[colors.hints.start]
background = "#303146"
foreground = "#d1d8f8"

[colors.hints.end]
background = "#303146"
foreground = "#d1d8f8"

[colors.line_indicator]
background = "#303146"
foreground = "#d1d8f8"

[colors.footer_bar]
background = "#303146"
foreground = "#d1d8f8"

[colors.selection]
background = "#414868"
foreground = "#d1d8f8"

[colors.normal]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[colors.bright]
black   = "#616682"
red     = "#fb91a1"
green   = "#b0d785"
yellow  = "#e7bd83"
blue    = "#95b2f9"
magenta = "#c8acf9"
cyan    = "#99d8ff"
white   = "#d1d8f8"

[colors.dim]
black   = "#363b55"
red     = "#c66073"
green   = "#7fa557"
yellow  = "#b38d55"
blue    = "#3d59a1"
magenta = "#967cc5"
cyan    = "#66a6cb"
white   = "#a9b1d6"

[window]
opacity         = 1.00
