black_dim = "#272833"
black = "#21222d"
black_bright = "#1c1d28"

red_dim = "#c66073"
red = "#f7768e"
red_bright = "#fb91a1"

pink_dim = "#a994c8"
pink = "#d3b8fb"
pink_bright = "#dbc5fc"

green_dim = "#7fa557"
green = "#9ece6a"
green_bright = "#b0d785"

yellow_dim = "#b38d55"
yellow = "#e0af68"
yellow_bright = "#e7bd83"

orange_dim = "#cc7f52"
orange = "#ff9e64"
orange_bright = "#ffb07f"

blue_dim = "#3d59a1"
blue = "#7aa2f7"
blue_bright = "#95b2f9"

purple_dim = "#967cc5"
purple = "#bb9af7"
purple_bright = "#c8acf9"

cyan_dim = "#66a6cb"
cyan = "#7dcfff"
cyan_bright = "#99d8ff"

white_dim = "#a9b1d6"
white = "#c0caf5"
white_bright = "#d1d8f8"

gray_dim = "#36363f"
gray = "#4f4f5d"
gray_bright = "#606071"

accent_dim = "#66a6cb"
accent = "#7dcfff"
accent_bright = "#99d8ff"

background_h = "#16161e"
background_0 = "#1a1b26"
background_1 = "#23242e"
background_2 = "#303146"
background_3 = "#424561"
background_4 = "#414868"
background_5 = "#565f89"

foreground_h = "#d1d8f8"
foreground_0 = "#c0caf5"
foreground_1 = "#a9b1d6"
foreground_2 = "#9aa5ce"
foreground_3 = "#8b95b9"
foreground_4 = "#7c85a5"
