$attention  = rgb(f7768e)

general {
  col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  col.inactive_border = rgb(303146)
}

misc {
  col.splash = rgb(1a1b26)
  background_color = rgb(1a1b26)
}
