black_dim = "#3b3538"
black = "#4f484b"
black_bright = "#645b5f"

red_dim = "#af3541"
red = "#da4453"
red_bright = "#e4656c"

pink_dim = "#bd7a81"
pink = "#eb99a1"
pink_bright = "#efa8af"

green_dim = "#bd7a81"
green = "#eb99a1"
green_bright = "#efa8af"

yellow_dim = "#bd7a81"
yellow = "#eb99a1"
yellow_bright = "#efa8af"

orange_dim = "#bd7a81"
orange = "#eb99a1"
orange_bright = "#efa8af"

blue_dim = "#bd7a81"
blue = "#eb99a1"
blue_bright = "#efa8af"

purple_dim = "#bd7a81"
purple = "#eb99a1"
purple_bright = "#efa8af"

cyan_dim = "#bd7a81"
cyan = "#eb99a1"
cyan_bright = "#efa8af"

white_dim = "#abaaad"
white = "#b8b7ba"
white_bright = "#c5c4c7"

gray_dim = "#40363a"
gray = "#544b4f"
gray_bright = "#645b5f"

accent_dim = "#bd7a81"
accent = "#eb99a1"
accent_bright = "#efa8af"

background_h = "#0e090b"
background_0 = "#120c0e"
background_1 = "#261a1e"
background_2 = "#40363a"
background_3 = "#473d41"
background_4 = "#4d4448"
background_5 = "#544b4f"

foreground_h = "#ebebed"
foreground_0 = "#d9d8dc"
foreground_1 = "#c5c4c7"
foreground_2 = "#b1b0b3"
foreground_3 = "#9d9c9f"
foreground_4 = "#8a898c"
