black_dim = "#252338"
black = "#2a283d"
black_bright = "#302e42"

red_dim = "#bc5b76"
red = "#eb6f92"
red_bright = "#f18ba5"

pink_dim = "#9d86b9"
pink = "#c4a7e7"
pink_bright = "#cfb7ec"

green_dim = "#36738d"
green = "#3e8fb0"
green_bright = "#67a3be"

yellow_dim = "#c59b61"
yellow = "#f6c177"
yellow_bright = "#f9cc90"

orange_dim = "#b66461"
orange = "#e37b78"
orange_bright = "#eb938f"

blue_dim = "#bb7c7a"
blue = "#ea9a97"
blue_bright = "#efaca9"

purple_dim = "#9d86b9"
purple = "#c4a7e7"
purple_bright = "#cfb7ec"

cyan_dim = "#7ea6ad"
cyan = "#9ccfd8"
cyan_bright = "#afd8df"

white_dim = "#a9a8b6"
white = "#c9c8db"
white_bright = "#e0def4"

gray_dim = "#4f4b7a"
gray = "#575287"
gray_bright = "#605a94"

accent_dim = "#bb7c7a"
accent = "#ea9a97"
accent_bright = "#efaca9"

background_h = "#191824"
background_0 = "#232136"
background_1 = "#2a273f"
background_2 = "#393552"
background_3 = "#454063"
background_4 = "#58537f"
background_5 = "#6c659a"

foreground_h = "#e0def4"
foreground_0 = "#c9c8db"
foreground_1 = "#a9a8b6"
foreground_2 = "#908caa"
foreground_3 = "#6e6a86"
foreground_4 = "#605c75"
