black_dim = "#1d1e20"
black = "#242628"
black_bright = "#363739"

red_dim = "#914141"
red = "#e16d77"
red_bright = "#e89299"

pink_dim = "#80455c"
pink = "#d67399"
pink_bright = "#de8fad"

green_dim = "#5c714d"
green = "#99bc80"
green_bright = "#adc999"

yellow_dim = "#8c6724"
yellow = "#dfbe81"
yellow_bright = "#e5cb9a"

orange_dim = "#836448"
orange = "#c99a6e"
orange_bright = "#d4ae8b"

blue_dim = "#447197"
blue = "#68aee8"
blue_bright = "#79b7eb"

purple_dim = "#854897"
purple = "#c27fd7"
purple_bright = "#ce99df"

cyan_dim = "#3e7278"
cyan = "#5fafb9"
cyan_bright = "#7fbfc7"

white_dim = "#7c7e82"
white = "#b1b4b9"
white_bright = "#c4c7ca"

gray_dim = "#404247"
gray = "#525355"
gray_bright = "#8b8d91"

accent_dim = "#447197"
accent = "#68aee8"
accent_bright = "#79b7eb"

background_h = "#242628"
background_0 = "#2c2d30"
background_1 = "#35373b"
background_2 = "#3e4045"
background_3 = "#404247"
background_4 = "#58595c"
background_5 = "#646568"

foreground_h = "#c4c7ca"
foreground_0 = "#b1b4b9"
foreground_1 = "#9ea0a5"
foreground_2 = "#8b8d91"
foreground_3 = "#78797c"
foreground_4 = "#646568"
