
layerrule = match:namespace notifications, animation slide

animations {
  bezier = easeOutQuint,     0.23, 1.0, 0.32, 1.0
  bezier = almostLinear,     0.50, 0.5, 0.75, 1.0
  bezier = linear,           0.00, 0.0, 1.00, 1.0

  #           What          on|off  speed bezier name  opts
  animation = border,        true,    2.5, easeOutQuint
  animation = fade,          true,    1.0, almostLinear

  animation = layers,        true,    1.5, easeOutQuint
  animation = fadeLayersIn,  true,    1.5, easeOutQuint
  animation = fadeLayersOut, true,    1.5, easeOutQuint

  animation = windows,       true,    1.25, easeOutQuint
  animation = windowsIn,     true,    2.25, easeOutQuint, popin 85%
  animation = windowsOut,    true,    2.25, easeOutQuint, popin 90%
  animation = workspaces,    true,    2.25, easeOutQuint, fade
}
