#!/usr/bin/env bash

exec </dev/tty

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

EXPECTED_PATH="$HOME/.local/share/vibranium/install"
VIBRANIUM="$HOME/.local/share/vibranium"

if [[ "$SCRIPT_DIR" != "$EXPECTED_PATH" ]]; then
  echo "ERROR: This script must be run from $EXPECTED_PATH" >&2
  echo "Current location: $SCRIPT_DIR" >&2
  echo ""
  echo "Please move the vibranium folder to ~/.local/share/vibranium and try again" >&2
  exit 1
fi

# Hide cursor
printf '\e[?25l'

# Source helpers
source "$SCRIPT_DIR/lib/helpers.sh"

# Move VT to the bottom
printf '\e[2J\e[%d;1H' "${LINES:-$(tput lines)}"

_show_logo

_log_info "Welcome to Vibranium, an Omarchy-like Arch Linux configuration"
_log_info "aimed to be simple, bazingly fast and highly customizable."
_log_info ""
_log_info "The installer will edit system files, install needed packages"
_log_info "and configure Vibranium specifically for your hardware."

if ! _ask_yes_no Y "Proceed with Installation?"; then
    _log_error "Installation aborted"
    exit 1
fi

if [[ $(hostnamectl chassis) == vm ]]; then
    _log_error "You are trying to install Vibranium inside of a virtual machine."
    _log_error "You may encounter unexpected bugs, slow performance, or not working WM at all."
    _log_error "You have been warned."

    if ! _ask_yes_no Y "I understand this."; then
        _log_error "Installation aborted"
        exit 1
    fi
fi

SUDO_PROMPT="$(printf '%s[VIBRANIUM]%s Password for %s: ' "$RED" "$RESET" "$USER")"
export SUDO_PROMPT

echo -e "${YELLOW}[VIBRANIUM]${RESET} Vibranium needs sudo to install packages"

if ! sudo -v; then
    _log_error "Installation aborted"
    exit 1
fi

YAY_PRESENT=false
CURRENT_STEP=0
TOTAL_STEPS=11

if _is_installed "yay"; then
    YAY_PRESENT=true
fi

if [[ "$YAY_PRESENT" == false ]]; then
    TOTAL_STEPS=$((TOTAL_STEPS + 1))
fi

mapfile -t PACKAGES < "$SCRIPT_DIR/pkgs.txt"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up system"
{
    bash "$SCRIPT_DIR/setup-system"
    bash "$SCRIPT_DIR/setup-tmpfiles"
    bash "$SCRIPT_DIR/setup-sysctl"
    bash "$SCRIPT_DIR/setup-zram"
}

# I want to install yay first,
# but we have to keep this step here for now
# because we're modifying the main pacman config above.
#
# Later I’ll reorder this so that pacman.conf
# and makepkg.conf are updated first,
# then yay is installed,
# and only after that system files / configs are set up.

[[ "$YAY_PRESENT" == false ]] && {
    CURRENT_STEP=$((CURRENT_STEP + 1))

    _log_info "[$CURRENT_STEP/$TOTAL_STEPS] Building and installing Yay AUR helper (this may take a moment)"
    _log_info "You may be asked for sudo multiple times"

    if ! _install_yay; then
        _log_error "Failed to install yay"
        _log_error "Aborting installation"
        exit 1
    fi
}

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing packages"
_install_packages "${PACKAGES[@]}"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up hardware"
bash "$SCRIPT_DIR/setup-hardware"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing themes (this may take a moment)"
bash "$SCRIPT_DIR/setup-gtk-themes"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing icons (this may take a moment)"
bash "$SCRIPT_DIR/setup-icons"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Copying configs"
bash "$SCRIPT_DIR/setup-configs"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up systemd services"
bash "$SCRIPT_DIR/setup-systemd"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up migrations"
bash "$SCRIPT_DIR/setup-migrations"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing default theme"
bash "$SCRIPT_DIR/setup-theme"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up mime types"
bash "$SCRIPT_DIR/setup-mimetypes"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Running post-install scripts"
bash "$SCRIPT_DIR/post-install"

_log_success "Installation complete. System restart required"
_log_success "You have to pick Hyprland (uwsm-managed) in your login manager. Otherwise Vibranium will NOT WORK"

if _ask_yes_no Y "Reboot now?"; then
    for sec in {5..1}; do
        for step in {0..3}; do
            dots=$(printf "%.*s" "$step" "...")
            printf "\r\033[K%s[VIBRANIUM]%s Restarting PC in %d%s" \
                "$YELLOW" "$RESET" "$sec" "$dots"
            sleep 0.25
        done
    done

    systemctl reboot
fi

# Show cursor
printf '\e[?25h'
