#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

# Ensure the dotfiles folder is in the correct location
EXPECTED_PATH="$HOME/.local/share/vibranium/install"
VIBRANIUM="$HOME/.local/share/vibranium"

if [[ "$SCRIPT_DIR" != "$EXPECTED_PATH" ]]; then
  echo "ERROR: This script must be run from $EXPECTED_PATH" >&2
  echo "Current location: $SCRIPT_DIR" >&2
  echo ""
  echo "Please move the vibranium folder to ~/.local/share/vibranium and try again" >&2
  exit 1
fi

# Source helpers
source "$SCRIPT_DIR/lib/helpers.sh"

SUDO_PROMPT="$(printf '%s[VIBRANIUM]%s Password for %s: ' "$RED" "$RESET" "$USER")"
export SUDO_PROMPT

# Switch to the latest release and re-exec
# if ! git branch | grep -q detached; then
#     git checkout -q --detach "$(git tag --sort=-creatordate | head -n 1)"
#     exec "$0"
#     exit 0
# fi

echo -e "${YELLOW}[VIBRANIUM]${RESET} Vibranium needs sudo to install packages"

if ! sudo -v; then
    exit 1
fi

clear

# Move VT to the bottom
printf '\e[2J\e[%d;1H' "${LINES:-$(tput lines)}"

# Hide cursor
printf '\e[?25l'

_show_logo

YAY_PRESENT=false
CURRENT_STEP=0

if _is_installed "yay"; then
    YAY_PRESENT=true
fi

if [[ "$YAY_PRESENT" == true ]]; then
    TOTAL_STEPS=12
else
    TOTAL_STEPS=11
fi

mapfile -t PACKAGES < "$SCRIPT_DIR/pkgs.txt"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up system"
{
    bash "$SCRIPT_DIR/setup-system"
    bash "$SCRIPT_DIR/setup-tmpfiles"
    bash "$SCRIPT_DIR/setup-sysctl"
    bash "$SCRIPT_DIR/setup-zram"
}

# I want to install yay first,
# but we have to keep this step here for now
# because we're modifying the main pacman config above.
#
# Later I’ll reorder this so that pacman.conf
# and makepkg.conf are updated first,
# then yay is installed,
# and only after that system files / configs are set up.

[[ "$YAY_PRESENT" == true ]] && {
    CURRENT_STEP=$((CURRENT_STEP + 1))
    _log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing yay AUR helper"
    _install_yay
}

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing packages"
_install_packages "${PACKAGES[@]}"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up hardware"
bash "$SCRIPT_DIR/setup-hardware"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing GTK themes"
bash "$SCRIPT_DIR/setup-gtk-themes"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing icon theme"
bash "$SCRIPT_DIR/setup-icons"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up directories"
bash "$SCRIPT_DIR/setup-dirs"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Copying configs"

mkdir -p "$HOME/.local/bin"
cp -r "$VIBRANIUM/config/"* "$HOME/.config/"
cp -r "$VIBRANIUM/extras/local/bin/"* "$HOME/.local/bin"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up systemd services"
bash "$SCRIPT_DIR/setup-systemd"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up migrations"
bash "$SCRIPT_DIR/setup-migrations"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing default theme"
bash "$SCRIPT_DIR/setup-theme"

CURRENT_STEP=$((CURRENT_STEP + 1))
_log_info "[$CURRENT_STEP/$TOTAL_STEPS] Finishing up"
bash "$SCRIPT_DIR/post-install"

_log_success "Installation complete. System restart required"

sleep 1

for i in {5..1}; do
    printf "\r\033[K%s[VIBRANIUM]%s Restarting PC in %d..." "$YELLOW" "$RESET" "$i"
    sleep 0.25
done

systemctl reboot
