#!/usr/bin/env bash

VIBRANIUM="$HOME/.local/share/vibranium"
CURRENT_BRANCH="$(git -C "$VIBRANIUM" branch --show-current)"

declare -A LINKS=(
    # It's probably not the best practice...
    ["$HOME/.local/share/vibranium/default/uwsm/env"]="$HOME/.config/uwsm/env"
)

LINKS_PERMS=(
    "$HOME/.config/hypr/hyprland.conf"
)

for src in "${!LINKS[@]}"; do
	ln -sf "$src" "${LINKS[$src]}" >/dev/null
done

for f in "${LINKS_PERMS[@]}"; do
    chmod ug-w "$f"
done

yay -Rnsc yay-debug --noconfirm &> /dev/null || true
yay -Scc --noconfirm &> /dev/null
yay -Ycc --noconfirm &> /dev/null

# Initial state for the hyprsunset
printf "suspended" > "$HOME/.local/state/vibranium/nightshift"

# Vibranium does not depend on the brightnessctl tool.
# It uses sysfs directly, so we need video group
if [ ! -z "$(find /sys/class/backlight -mindepth 1 -maxdepth 1 2>/dev/null)" ]; then
    sudo usermod -aG video "$USER"
fi

# First run marker
: > "$HOME/.local/state/vibranium/first-run"

mkdir -p "$HOME/.config/vibranium/startup"
mkdir -p "$HOME/.config/vibranium/shutdown"


if [[ "$CURRENT_BRANCH" =~ v* ]]; then
    printf "%s" "release" > \
        "$HOME/.local/state/vibranium/update.channel"
elif [[ "$CURRENT_BRANCH" == "dev" ]]; then
    printf "%s" "dev" > \
        "$HOME/.local/state/vibranium/update.channel"
else
    printf "%s" "upstream" > \
        "$HOME/.local/state/vibranium/update.channel"
fi

