#!/usr/bin/env bash

PACMAN_CONF="/etc/pacman.conf"
MAKEPKG_CONF="/etc/makepkg.conf"
SUDOERS_CONF="/etc/sudoers.d/vibranium"
FAILLOCK_CONF="/etc/security/faillock.conf"
SYSTEM_AUTH_CONF="/etc/pam.d/system-auth"
LOGIND_CONF="/etc/systemd/logind.conf"

VIBRANIUM="$HOME/.local/share/vibranium"

# pacman hooks
# polkit rule (sudoless mounting)
# v4l loopback (aka virtual camera)
sudo cp -r "$VIBRANIUM"/extras/etc/* /etc/

# Power plug / USB notifications
sudo cp -r "$VIBRANIUM"/extras/etc/udev/rules.d /etc/udev/

# Auxiliary scripts (executed in the udev rules)
sudo cp -r "$VIBRANIUM"/extras/usr/local/bin/* /usr/local/bin/

sudo sed -i "s/user_placeholder/$USER/g" /usr/local/bin/*

####################################################################

if [[ ! -d /etc/sudoers.d ]]; then
    sudo mkdir /etc/sudoers.d
fi

# Don't let systemd habdle hardware power button.
# We will map it in WM's settings
sudo sed -Ei '/^#?HandlePowerKey=/s/^#//;/HandlePowerKey/s/=.*/=ignore/' "$LOGIND_CONF"

# Enable 32-bit support
grep -qE '^\[multilib\]' "$PACMAN_CONF" ||
sudo sed -Ei '/\[multilib\]/,/^$/s/^#//' "$PACMAN_CONF"
sudo sed -i '/^#NoExtract/ s/^#//' "$PACMAN_CONF"

# Remove the default wallpaper plugin, which works only in XFCE
# It will be replaced with the vibranium script
sudo sed -i '/^NoExtract/ s|$| usr/lib/thunarx-3/thunar-wallpaper-plugin.so|' "$PACMAN_CONF"
sudo rm -f /usr/lib/thunarx-3/thunar-wallpaper-plugin.so

# Use colorized output by default
grep -q '^Color' "$PACMAN_CONF" ||
sudo sed -Ei 's/^\s*#?Color/Color/' "$PACMAN_CONF"

# Use verbose pacckage list by default
grep -q '^VerbosePkgLists' "$PACMAN_CONF" ||
sudo sed -Ei 's/^\s*#?VerbosePkgLists/VerbosePkgLists/' "$PACMAN_CONF"

# Use parallel downloads (speeds up download time)
grep -q '^ParallelDownloads = 10' "$PACMAN_CONF" ||
sudo sed -Ei 's/^\s*#?ParallelDownloads.*/ParallelDownloads = 10/' "$PACMAN_CONF"

# Always compile AUR packages for native CPU microarchitecture
grep -q '\-march=native' "$MAKEPKG_CONF" ||
sudo sed -Ei 's/-march=x86-64/-march=native/' "$MAKEPKG_CONF"

# Do not install debug packages
grep -Eq '^OPTIONS=.*\bdebug\b' "$MAKEPKG_CONF" &&
sudo sed -Ei '/^OPTIONS=/ s/(^|[[:space:]])!?debug(\b)/\1!debug\2/' "$MAKEPKG_CONF"

# sudo: show asterisk symbols when entering a password
sudo grep -qxF '## VIBRANIUM: Enable interactive prompt' "$SUDOERS_CONF" 2> /dev/null ||
echo -e '\n## VIBRANIUM: Enable interactive prompt\nDefaults env_reset,pwfeedback' |
sudo tee -a "$SUDOERS_CONF" >/dev/null

# Increase failed sudo attemps to five
grep -qxF 'nodelay' "$FAILLOCK_CONF" ||
echo -e 'deny = 5\nnodelay' | sudo tee -a "$FAILLOCK_CONF" >/dev/null

# Completely remove delay between sudo attemps after entering wrong password
sudo grep -q '^auth.*pam_unix\.so.*try_first_pass nullok nodelay' "$SYSTEM_AUTH_CONF" ||
sudo sed -Ei '/^auth.*pam_unix\.so.*try_first_pass nullok/ s/\bnullok\b/& nodelay/' "$SYSTEM_AUTH_CONF"

