#!/usr/bin/env bash

set -Eeuo pipefail

VIBRANIUM_DIR="$HOME/.local/share/vibranium"
ICONS_DIR="$HOME/.local/share/icons"
BIN_DIR="$HOME/.local/bin"
CACHE_DIR="$HOME/.cache"

PAPIRUS_REPO="https://github.com/PapirusDevelopmentTeam/papirus-icon-theme.git"
PAPIRUS_FOLDERS_URL="https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-folders/refs/heads/master/papirus-folders"

YELLOW=$'\e[0;33m'
RESET=$'\e[0m'

cleanup() {
    [[ -n "${PAPIRUS_TMP_DIR:-}" && -d "$PAPIRUS_TMP_DIR" ]] && rm -rf "$PAPIRUS_TMP_DIR"
}

trap cleanup EXIT

mkdir -p "$ICONS_DIR" "$BIN_DIR"

PAPIRUS_TMP_DIR="$(mktemp -d "$CACHE_DIR/papirus.XXXXXX")"
git clone -q "$PAPIRUS_REPO" "$PAPIRUS_TMP_DIR"

cp -r "$PAPIRUS_TMP_DIR"/Papirus* "$ICONS_DIR"

curl -fsSL "$PAPIRUS_FOLDERS_URL" -o "$BIN_DIR/papirus-folders"
chmod +x "$BIN_DIR/papirus-folders"

cp -r "$VIBRANIUM_DIR/extras/icon_theme/Vibranium" "$ICONS_DIR"

ln -sf "$HOME/.local/share/icons" "$HOME/.icons"
