#!/usr/bin/env bash

mkdir -p \
    "$HOME"/.config/{Vencord,vesktop}/{themes,settings} \
    "$HOME"/.config/heroic/{themes,store} \
    "$HOME"/.config/qt{5,6}ct/colors \
    "$HOME/.config/spicetify/Themes/text" \
    "$HOME/.config/hypr/hyprland.conf.d" \
    "$HOME/.local/share/applications" \
    "$HOME/.local/state/vibranium/" \
    "$HOME/.config/vibranium/theme" \
    "$HOME/.config/btop/themes/" \
    "$HOME/.config/discord" \
    "$HOME/.config/wlogout" \
    "$HOME/.config/gtk-3.0" \
    "$HOME/.config/gtk-4.0" \
    "$HOME/.config/zathura" \
    "$HOME/.config/swayosd" \
    "$HOME/.config/dunst" \
    "$HOME/.config/uwsm" \
    "$HOME/.config/imv"
