#!/usr/bin/env bash

case "$(</sys/class/dmi/id/chassis_type)" in
    9|10|14)  # Laptop, Notebook, Sub-Notebook
        ZRAM_SIZE="ram / 2"
        ;;
    *)  # Desktop / Other
        ZRAM_SIZE="ram"
        ;;
esac

sudo tee /etc/systemd/zram-generator.conf >/dev/null <<EOF
[zram0]
zram-size = $ZRAM_SIZE
compression-algorithm = lzo-rle zstd(level=3) (type=idle)
EOF

