black_dim = "#1f2223"
black = "#242728"
black_bright = "#2a2d2e"

red_dim = "#9d0006"
red = "#cc241d"
red_bright = "#fb4934"

pink_dim = "#8f3f71"
pink = "#b16286"
pink_bright = "#d3869b"

green_dim = "#797814"
green = "#98971a"
green_bright = "#b8bb26"

yellow_dim = "#b57614"
yellow = "#d79921"
yellow_bright = "#fabd2f"

orange_dim = "#af3a03"
orange = "#d65d0e"
orange_bright = "#fe8019"

blue_dim = "#076678"
blue = "#458588"
blue_bright = "#83a598"

purple_dim = "#8f3f71"
purple = "#b16286"
purple_bright = "#d3869b"

cyan_dim = "#427b58"
cyan = "#689d6a"
cyan_bright = "#8ec07c"

white_dim = "#d5c4a1"
white = "#ebdbb2"
white_bright = "#fbf1c7"

gray_dim = "#4c4745"
gray = "#57514e"
gray_bright = "#625c58"

accent_dim = "#79740e"
accent = "#98971a"
accent_bright = "#b8bb26"

background_h = "#211e1d"
background_0 = "#1d2021"
background_1 = "#282828"
background_2 = "#3c3836"
background_3 = "#504945"
background_4 = "#665c54"
background_5 = "#7c6f64"

foreground_h = "#ebdbb2"
foreground_0 = "#d5c4a1"
foreground_1 = "#bdae93"
foreground_2 = "#a89984"
foreground_3 = "#978a77"
foreground_4 = "#887d6c"
