#!/bin/bash

REFRESH_RATE="$(hyprctl -j monitors | jq -r 'max_by(.refreshRate) | (.refreshRate + 0.5 | floor)')"

cat <<EOF >"$XDG_CONFIG_HOME/hypr/xdph.conf"
# This file was auto-generated by the Vibranium post-install hooks.
# The max_fps value was set to match the highest refresh rate
# available across all your monitors.
# You can safely change it if needed.

screencopy {
  max_fps = $REFRESH_RATE
  allow_token_by_default = true
}
EOF

systemctl --user restart xdg-desktop-portal-hyprland
