#!/usr/bin/env bash

# Dynamically adjust idle times based on the machine type
case "$(hostnamectl chassis)" in
    laptop|tablet|convertible)
        # 2 minutes
        LOCK_AFTER=120
        # 5 minutes
        SLEEP_AFTER=300
        # set type
        MACHINE_TYPE="Portable (laptop/tablet)"
        ;;

    # Desktop / Other
    *)
        # 10 minutes
        LOCK_AFTER=600
        # 15 minutes
        SLEEP_AFTER=900
        # set type
        MACHINE_TYPE="Desktop/VM/any other"
        ;;
esac

cat <<EOF > "$XDG_CONFIG_HOME/hypr/hypridle.conf"
# This file was auto-generated by the Vibranium post-install hooks.
# Timeout settings were chosen according to your machine type.
# Detected machine type: $MACHINE_TYPE
#
# For portable devices, shorter timeouts are applied
# (for example, on the go or in public spaces)

# The timers are parsed from top to bottom.
#
# The first timer is responsible for the number of seconds
# of inactivity after which the session will be locked (lock screen).
#
# The second timer is responsible for the number of seconds
# of inactivity after which the machine will go to sleep (suspend).

# Do not edit this file manually!
# Instead, use the Vibranium Menu > Settings > Idle

source = ~/.local/share/vibranium/default/hypr/hypridle.conf

listener {
timeout = $LOCK_AFTER
on-timeout = loginctl lock-session
}

listener {
	timeout = $SLEEP_AFTER
	on-timeout = systemctl suspend
}

EOF

systemctl --user restart hypridle
