#!/usr/bin/env bash

REFRESH_RATE="$(hyprctl -j monitors | jq -r '.[] | select(.focused) | (.refreshRate + 0.5 | floor)')"

cat <<EOF > "$XDG_CONFIG_HOME/hypr/xdph.conf"
# This file was auto-generated by the Vibranium post-install hooks.
# The max_fps value was set to match the highest refresh rate
# of the focused monitor at first launch.
# You can safely change it if needed.

screencopy {
    max_fps = $REFRESH_RATE
	allow_token_by_default = true
}
EOF

killall -e xdg-desktop-portal-hyprland
exec setsid -f /usr/lib/xdg-desktop-portal-hyprland &> /dev/null
