#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

_build() {
  cfgr::item::string \
    --var VIBRANIUM_SCREENSHOT_FILE_TYPE \
    --label "Filetype" \
    --title "Filetype" \
    --option "PNG:png" "JPEG:jpeg" "PPM:ppm"

  if [[ "$VIBRANIUM_SCREENSHOT_FILE_TYPE" == "jpeg" ]]; then
    cfgr::item::digit \
      --var VIBRANIUM_SCREENSHOT_JPEG_QUALITY \
      --label "JPEG quality" \
      --title "JPEG Quality" \
      --prompt "Quality (int)" \
      --type int \
      --min 1 \
      --max 100
  fi

  if [[ "$(hyprctl getoption animations:enabled)" =~ 1 ]]; then
    cfgr::item::bool \
      --var VIBRANIUM_SCREENSHOT_FLASH_SCREEN \
      --label "Flash screen"

    cfgr::item::bool \
      --var VIBRANIUM_SCREENSHOT_FLASH_BORDER \
      --label "Flash border"
  fi

  cfgr::item::bool \
    --var VIBRANIUM_SCREENSHOT_SAVE_TO_DISK \
    --label "Save to disk"

  cfgr::item::bool \
    --var VIBRANIUM_SCREENSHOT_CAPTURE_CURSOR \
    --label "Capture cursor"

  cfgr::item::bool \
    --var VIBRANIUM_SCREENSHOT_SHOW_NOTIFICATION \
    --label "Show notification"

  cfgr::item::bool \
    --var VIBRANIUM_SCREENSHOT_AUTO_ANNOTATE \
    --label "Annotate automatically"
}

cfgr::run "Screenshots" "_build" \
  VIBRANIUM_SCREENSHOT_FILE_TYPE \
  VIBRANIUM_SCREENSHOT_JPEG_QUALITY \
  VIBRANIUM_SCREENSHOT_FLASH_BORDER \
  VIBRANIUM_SCREENSHOT_FLASH_SCREEN \
  VIBRANIUM_SCREENSHOT_SAVE_TO_DISK \
  VIBRANIUM_SCREENSHOT_AUTO_ANNOTATE \
  VIBRANIUM_SCREENSHOT_CAPTURE_CURSOR \
  VIBRANIUM_SCREENSHOT_SHOW_NOTIFICATION
