#!/usr/bin/env bash

source vb-lib-core
export PATH="$PATH:$VIBRANIUM/configure"

INDEX=0

while true; do
  OPTIONS=("<b>Input</b>" "<b>Appearance</b>" "<b>Edit configs</b>" "<b>Advanced</b>")
  helpers::ui::menu CHOSEN "Hyprland" "ESC to go back" -selected-row "$INDEX" -- "${OPTIONS[@]}"
  [[ -z $CHOSEN ]] && break

  for i in "${!OPTIONS[@]}"; do
    if [ "${OPTIONS[$i]}" == "$CHOSEN" ]; then
      INDEX="$i"
      break
    fi
  done

  case "$CHOSEN" in
    *"Appearance"*)
      cfgr-wm-appearance
      ;;
    *"Advanced"*)
      cfgr-wm-advanced
      ;;
    *"Input"*)
      cfgr-wm-input
      ;;
    *"Edit configs"*)
      while true; do
        edit_configs_opts=(
          "<b><i>Input</i></b>"
          "<b><i>Window rules</i></b>"
          "<b><i>Keybindings</i></b>"
          "<b><i>Monitors</i></b>"
        )
        helpers::ui::menu edit_configs_chosen "Edit" "ESC to go back" -- "${edit_configs_opts[@]}"
        [[ -z $edit_configs_chosen ]] && break

        case "$edit_configs_chosen" in
          *"Window rules"*) vb-core-term -- "$EDITOR" "$XDG_CONFIG_HOME/hypr/hyprland.conf.d/window-rules.conf" ;;
          *"Keybindings"*) vb-core-term -- "$EDITOR" "$XDG_CONFIG_HOME/hypr/hyprland.conf.d/binds.conf" ;;
          *"Monitors"*) vb-core-term -- "$EDITOR" "$XDG_CONFIG_HOME/hypr/hyprland.conf.d/monitors.conf" ;;
          *"Input"*) vb-core-term -- "$EDITOR" "$XDG_CONFIG_HOME/hypr/hyprland.conf.d/input.conf" ;;
        esac
        helpers::ui::close_menus
      done
      ;;
  esac
done
