#!/bin/bash

_set_update_channel() {
  local chosen
  chosen="$(cfgr::set_string \
    --title "Update Channel" \
    --option "Release:release" "Upstream:upstream")"
  vb-dev-switch-channel "$chosen"
}

_get_update_channel() {
  local branch
  branch="$(git -C "$VIBRANIUM" branch --show-current 2>/dev/null)"
  case "$branch" in
    master) echo "Upstream" ;;
    *)      echo "Release" ;;
  esac
}

_get_vb_updates (){
  local file="$XDG_CONFIG_HOME/systemd/user/default.target.wants/vibranium-update.timer"

  if [[ -L "$file" ]]; then
    return 0
  else
    return 1
  fi
}

_toggle_vb_updates (){
  if _get_vb_updates; then
    systemctl -q --user disable --now vibranium-update.timer
  else
    systemctl -q --user enable --now vibranium-update.timer
  fi
}

_build() {
  local update_channel
  update_channel="$(_get_update_channel)"

  if _get_vb_updates; then
    local vb_updates_enabled="true"
  else
    local vb_updates_enabled="false"
  fi

  cfgr::item::raw "Update channel : $update_channel" "action:_set_update_channel"
  cfgr::item::raw "Updates auto check : $vb_updates_enabled" "action:_toggle_vb_updates"
}

cfgr::run "General" "_build" \
  VIBRANIUM_GLOBAL_CONFIRM_TO_KILL
