#!/bin/bash


WAYBAR_CFG="$XDG_CONFIG_HOME/waybar/config.jsonc"
_CFG_CONTENT=""

_load_cfg() {
  _CFG_CONTENT=$(<"$WAYBAR_CFG")
}

_module_in_cfg() {
  local module="$1"
  [[ "$_CFG_CONTENT" == *"\"$module\""* ]]
}

_updates_weather_menu() {
  _update() {
    vb-refresh-waybar-module pacman &
    vb-refresh-waybar-module weather &
  }

  _u_w_build() {
    cfgr::item::bool \
      --var VIBRANIUM_BAR_SHOW_ANIMATION \
      --label "Animate first launch"
  }

  cfgr::run "Updates & Weather" "_u_w_build" \
    VIBRANIUM_BAR_SHOW_ANIMATION
}

_monitoring_menu() {
  _m_build() {
    _module_in_cfg 'custom/ram' && cfgr::item::string \
      --var VIBRANIUM_BAR_RAM_MODE \
      --label "RAM display" \
      --title "RAM format" \
      --option "Percent:perc" "KiB:KiB" "MiB:MiB" "GiB:GiB" "KB:KB" "MB:MB" "GB:GB" \
      --hook "vb-refresh-waybar-module ram"

    _module_in_cfg 'custom/disk' && cfgr::item::string \
      --var VIBRANIUM_BAR_DISK_MODE \
      --label "Disk display" \
      --title "Disk format" \
      --option "Percent:perc" "KiB:KiB" "MiB:MiB" "GiB:GiB" "KB:KB" "MB:MB" "GB:GB" \
      --hook "vb-refresh-waybar-module disk"


  }

  cfgr::run "Monitoring" "_m_build" \
    VIBRANIUM_BAR_RAM_MODE \
    VIBRANIUM_BAR_DISK_MODE
}

_build() {
  if _module_in_cfg 'custom/weather' || _module_in_cfg 'custom/pacman'; then
    cfgr::item::action \
      --func "_updates_weather_menu" \
      --label "Updates / Weather"
  fi

  if _module_in_cfg 'custom/ram' || _module_in_cfg 'custom/disk' \
    || _module_in_cfg 'custom/cpu-temp' || _module_in_cfg 'custom/gpu-temp'; then
    cfgr::item::action \
      --func "_monitoring_menu" \
      --label "Monitoring"
  fi
}

_load_cfg

if ! _module_in_cfg 'custom/weather' && ! _module_in_cfg 'custom/pacman' \
  && ! _module_in_cfg 'custom/ram' && ! _module_in_cfg 'custom/disk' \
  && ! _module_in_cfg 'custom/cpu-temp' && ! _module_in_cfg 'custom/gpu-temp'; then
  notify-send -r 1 -u normal "Vibranium" "No configurable modules are present in your Waybar config."
  exit 0
fi

cfgr::run "Modules" "_build"
