#!/usr/bin/env bash

source vb-core-lib

INDEX=0


while true; do
    source "$VIBRANIUM_USER_SETTINGS"

    helpers::check VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_AI
    helpers::check VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ICONS
    helpers::check VIBRANIUM_GLOBAL_APP_LAUNCHER_AUTO_SELECT
    helpers::check VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_WEBAPPS
    helpers::check VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ON_START
    helpers::check VIBRANIUM_GLOBAL_SEARCH_ENGINE google

    OPTIONS=(
        "Search engine : $VIBRANIUM_GLOBAL_SEARCH_ENGINE"
        "Show web apps : $VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_WEBAPPS"
        "Show AI web apps : $VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_AI"
        "Show app icons : $VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ICONS"
        "Open on startup : $VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ON_START"
        "Auto select : $VIBRANIUM_GLOBAL_APP_LAUNCHER_AUTO_SELECT"
    )

    mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
    helpers::ui::menu CHOSEN "App Launcher" "ESC to go back" -selected-row "$INDEX" -- "${OPTIONS[@]}"
    [ -z "$CHOSEN" ] && break

    for i in "${!OPTIONS[@]}"; do
        if [[ "${OPTIONS[$i]}" == "$CHOSEN" ]]; then
            INDEX="$i"
            break
        fi
    done

    case "$CHOSEN" in
        "Search engine"*)
            helpers::configure::set_string VIBRANIUM_GLOBAL_SEARCH_ENGINE "Search Engine" \
                "Google:google" \
                "DuckDuckGo:duckduckgo" \
                "Brave Search:brave" \
                "Microsoft Bing:bing"
            ;;
        "Show web apps"*)
            helpers::configure::toggle_bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_WEBAPPS
            ;;
        "Show AI"*)
            helpers::configure::toggle_bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_AI
            ;;
        "Show app icons"*)
            helpers::configure::toggle_bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ICONS
            ;;
        "Open on startup"*)
            helpers::configure::toggle_bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ON_START
            ;;
        "Auto select"*)
            helpers::configure::toggle_bool VIBRANIUM_GLOBAL_APP_LAUNCHER_AUTO_SELECT
            ;;
    esac
done
