#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

# _update_module_setting() {
#   local var="$1"
#   local type="$2"
#   local rofi_title="$3"
#   local rofi_subtitle="$4"
#   local validation_regex="$5"
#   local error_message="$6"
#   local quote_value="$7"
#   local module_name="$8"
#   local enabled_var="$9"
#
#   local current_value="${!var}"
#   rofi_subtitle="${rofi_subtitle//\{current\}/$current_value}"
#
#   while true; do
#     helpers::ui::menu new_value "$rofi_title" "$rofi_subtitle" -- "Enter new value ($type)"
#     [ -z "$new_value" ] && break
#
#     if [[ ! "$new_value" =~ $validation_regex ]]; then
#       if [[ -n "$error_message" ]]; then
#         notify-send -r 1 -u critical -t 2000 "Vibranium" "$error_message"
#       fi
#       continue
#     fi
#
#     helpers::configure::verify_option "$var"
#
#     if [[ "$quote_value" == "yes" ]]; then
#       sed -i "s|^${var}=.*|${var}=\"${new_value}\"|" "$VIBRANIUM_USER_SETTINGS"
#     else
#       sed -i "/^${var}/s/=.*/=${new_value}/" "$VIBRANIUM_USER_SETTINGS"
#     fi
#
#     if [[ "${!enabled_var}" == false ]]; then
#       notify-send -r 1 -t 5000 "Vibranium" \
#         "The value has been changed. Don't forget to enable the module."
#     fi
#
#     vb-cmd-refresh-bar-module "$module_name" &
#     break
#   done
# }

_updates_weather_menu() {
  _update() {
    vb-cmd-refresh-bar-module pacman &
    vb-cmd-refresh-bar-module weather &
  }

  _u_w_build() {
    cfgr::item::bool \
      --var   VIBRANIUM_BAR_SHOW_ANIMATION \
      --label "Animate first launch"

    cfgr::item::bool \
      --var   VIBRANIUM_BAR_SHOW_SEPARATOR \
      --label "Show separators" \
      --hook  "_update"
  }

  cfgr::run "Updates & Weather" "_u_w_build" \
    VIBRANIUM_BAR_SHOW_ANIMATION \
    VIBRANIUM_BAR_SHOW_SEPARATOR
}

_updates_menu() {
  _u_build() {
    cfgr::item::bool \
      --var   VIBRANIUM_BAR_PACMAN_MODULE_SHOW_ZERO_UPDATES \
      --label "Display when up to date" \
      --hook  "vb-cmd-refresh-bar-module pacman &"
  }

  cfgr::run "Updates" "_u_build" VIBRANIUM_BAR_PACMAN_MODULE_SHOW_ZERO_UPDATES
}

_build() {
  cfgr::item::action \
    --func  "_updates_weather_menu" \
    --label "Updates / Weather specific"

  cfgr::item::action \
    --func  "_updates_menu" \
    --label "Updates"
}

cfgr::run "Modules" "_build"
