#!/usr/bin/env bash

source vb-core-lib

INDEX=0

STATE_FILE="$XDG_STATE_HOME/vibranium/nightshift"
CONFIG_FILE="$XDG_CONFIG_HOME/hypr/hyprsunset.conf"

if [ ! -f "$STATE_FILE" ]; then
    if hyprctl hyprsunset &> /dev/null; then
        echo "active" > "$STATE_FILE"
    else
        echo "suspended" > "$STATE_FILE"
    fi
fi

while true; do
    is_active="$(< "$STATE_FILE")"
    temperature_current="$(sed -n 's/.*temperature[[:space:]]*=[[:space:]]*\(.*\)/\1/p' "$CONFIG_FILE")"

    OPTIONS=("State : $is_active")

    if [[ "$is_active" == active ]]; then
        OPTIONS+=("Temperature : ${temperature_current}K")
    fi

    mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
    helpers::ui::menu CHOSEN "Night Light" "ESC to go back" -selected-row "$INDEX" -- "${OPTIONS[@]}"
    [ -z "$CHOSEN" ] && break

    for i in "${!OPTIONS[@]}"; do
        if [ "${OPTIONS[$i]}" == "$CHOSEN" ]; then
            INDEX="$i"
            break
        fi
    done

    case "$CHOSEN" in
        "State"*)
            vb-cmd-nightshift --toggle
            vb-cmd-refresh-bar-module nightshift
            ;;
        "Temperature"*)
            new_value="$(helpers::configure::set_digit --verify "Night Light Temperature (K)" "Temperature" "int" 1000 20000)"
            if [[ -n "$new_value" ]]; then
                vb-cmd-nightshift --set "$new_value"
            fi
            ;;
    esac
done
