#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

export PATH="$PATH:$VIBRANIUM/configure"

_build() {
  cfgr::item::action "cfgr-idle" "Idle"
  cfgr::item::action "cfgr-audio" "Audio"
  cfgr::item::action "cfgr-waybar-menu" "Waybar"
  cfgr::item::action "cfgr-general" "General"
  cfgr::item::action "vb-font-set" "Set Font"
  cfgr::item::action "cfgr-wm-menu" "Hyprland"
  cfgr::item::action "cfgr-recording" "Recording"

  if [[ "$CHASSIS_TYPE" != vm ]]; then
    cfgr::item::action "cfgr-brightness" "Brightness"
    cfgr::item::action "cfgr-nightshift" "Night Light"
  fi

  cfgr::item::action "cfgr-screenshots" "Screenshots"
  cfgr::item::action "cfgr-color-picker" "Color Picker"
  cfgr::item::action "cfgr-misc" "Miscellaneous"
}

cfgr::run "Settings" "_build"
