#!/usr/bin/env bash

source vb-lib-hypr

ADVANCED_SPEC=(
  "misc.vrr|int"
  "debug.vfr|bool"
  "misc.middle_click_paste|bool"
  "render.direct_scanout|bool"
  "misc.disable_autoreload|bool"
  "general.layout|str"
  "cursor.zoom_detached_camera|bool"
)

_set_vrr() {
  local chosen
  chosen="$(cfgr::set_string \
    --title "VRR" \
    --option "Enable:1" \
             "Disable:0" \
             "Fullscreen only:2"
  )"

  hypr::set "misc:vrr" "$chosen" "$HYPR_CONF_ADVANCED"
}

_set_layout() {
  chosen="$(cfgr::set_string \
    --title "Windows Layout" \
    --option "Dwindle:dwindle" \
             "Master:master" \
             "Scrolling:scrolling"
  )"
  hypr::set "general:layout" "$chosen" "$HYPR_CONF_ADVANCED"
}

_toggle() {
  local path="$1"
  hypr::toggle "$path" "$HYPR_CONF_ADVANCED"
}

_build() {
  hypr::reload
  hypr::fetch "${ADVANCED_SPEC[@]}"

  # VRR has 3 states, map int -> display string
  local vrr_display=
  case "${HYPR[misc:vrr]}" in
    1) vrr_display=enabled ;;
    0) vrr_display=disabled ;;
    *) vrr_display="Fullscreen only" ;;
  esac

  cfgr::item::action \
    --label "Variable refresh rate : ${vrr_display}" \
    --func "_set_vrr"

  cfgr::item::action \
    --label "Zoom detached camera : ${HYPR[cursor.zoom_detached_camera]}" \
    --func "_toggle 'cursor:zoom_detached_camera'"

  cfgr::item::action \
    --label "Variable frame rate : ${HYPR[misc.vfr]}" \
    --func "_toggle 'debug:vfr'"

  cfgr::item::action \
    --label "Disable auto reload : ${HYPR[misc.disable_autoreload]}" \
    --func "_toggle 'misc:disable_autoreload'"

  cfgr::item::action \
    --label "Middle click paste : ${HYPR[misc.middle_click_paste]}" \
    --func "_toggle 'misc:middle_click_paste'"

  cfgr::item::action \
    --label "Direct scanout : ${HYPR[render.direct_scanout]}" \
    --func "_toggle 'render:direct_scanout'"

  cfgr::item::action \
    --label "Layout : ${HYPR[general.layout]^}" \
    --func "_set_layout"
}

cfgr::run "Advanced" "_build"
