#!/usr/bin/env bash


_build() {
  cfgr::item::bool \
    --var VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL \
    --label "Use DDC protocol"

  cfgr::item::bool \
    --var VIBRANIUM_BRIGHTNESS_NOTIFY \
    --label "Show notificaation"

  cfgr::item::digit \
    --var VIBRANIUM_BRIGHTNESS_STEP \
    --prompt "Brightnes step" \
    --label "Brightnes step" \
    --title "Brightness" \
    --type int \
    --min 1 \
    --max 25
}

cfgr::run "Brightness" "_build" \
  VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL \
  VIBRANIUM_BRIGHTNESS_NOTIFY \
  VIBRANIUM_BRIGHTNESS_STEP
