#!/usr/bin/env bash


_build() {
  cfgr::item::string \
    --var    VIBRANIUM_PLAYER_FADE_DURATION_ON_SWITCH \
    --label  "Fade in / out on Next / Previous" \
    --title  "Fade duration" \
    --option "Very Slow:very_slow" "Slow:slow" "Normal:normal" \
             "Fast:fast" "Very Fast:very_fast" "OFF:off"

  cfgr::item::string \
    --var    VIBRANIUM_PLAYER_FADE_DURATION \
    --label  "Fade in / out on Play / Pause" \
    --title  "Fade duration" \
    --option "Very Slow:very_slow" "Slow:slow" "Normal:normal" \
             "Fast:fast" "Very Fast:very_fast" "OFF:off"

  cfgr::item::action \
    --func  "vb-cmd-show-help player-fade" \
    --label "Help"
}

cfgr::run "Media Controls" "_build" \
  VIBRANIUM_PLAYER_FADE_DURATION \
  VIBRANIUM_PLAYER_FADE_DURATION_ON_SWITCH
