#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

_advanced_menu() {
  _a_build() {
    cfgr::item::string VIBRANIUM_RECORDING_VIDEO_CODEC "Video codec" "Codec" \
      "Auto:auto" "H264:h264" "HEVC:hevc" "AV1:av1" "VP8:vp8" "VP9:vp9" "HEVC (HDR):hevc_hdr" \
      "AV1 (HDR):av1_hdr" "HEVC (10 bit color):hevc_10bit" "AV1 (10 bit color):av1_10bit"
    cfgr::item::string VIBRANIUM_RECORDING_FRAMERATE_MODE "Framerate mode" "Mode" \
      "Constant Frame Rate:cfr" "Variable Frame Rate:vfr"
    cfgr::item::string VIBRANIUM_RECORDING_CONTAINER_TYPE "Container type" "Filetype" \
      "mp4" "webm" "mkv"
    cfgr::item::bool VIBRANIUM_RECORDING_FLASH_SCREEN "Flash screen"
  }

  cfgr::run "Advanced" "_a_build" \
    VIBRANIUM_RECORDING_FRAMERATE_MODE \
    VIBRANIUM_RECORDING_CONTAINER_TYPE \
    VIBRANIUM_RECORDING_FLASH_SCREEN \
    VIBRANIUM_RECORDING_VIDEO_CODEC
}

_build() {
  cfgr::item::string VIBRANIUM_RECORDING_QUALITY "Recording quality" "Quality" \
    "Medium:medium" "High:high" "Very High:very_high" "Ultra:ultra"
  cfgr::item::bool VIBRANIUM_RECORDING_CAPTURE_SINK "Capture output"
  cfgr::item::bool VIBRANIUM_RECORDING_CAPTURE_SOURCE "Capture input"
  cfgr::item::digit VIBRANIUM_RECORDING_FPS "FPS" "FPS to record with (int)" "FPS" int 15 120
  cfgr::item::action "_advanced_menu" "Advanced"
}

cfgr::run "Recording" "_build" \
  VIBRANIUM_RECORDING_FPS \
  VIBRANIUM_RECORDING_QUALITY \
  VIBRANIUM_RECORDING_CAPTURE_SINK \
  VIBRANIUM_RECORDING_CAPTURE_SOURCE
