#!/usr/bin/env bash

source vb-core-lib

INDEX=0


while true; do
    source "$VIBRANIUM_USER_SETTINGS"

    helpers::check VIBRANIUM_GLOBAL_RESPECT_POWER_PROFILE
    helpers::check VIBRANIUM_GLOBAL_POWER_PROFILE_USE_FEEDBACK

    OPTIONS=(
        "Respect power profile : $VIBRANIUM_GLOBAL_RESPECT_POWER_PROFILE"
        "Visual feedback : $VIBRANIUM_GLOBAL_POWER_PROFILE_USE_FEEDBACK"
    )

    mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
    CHOSEN="$(printf "%s\n" "${OPTIONS[@]}" | helpers::ui::menu "Power profiles" "ESC to go back" -selected-row "$INDEX")"
    [[ -z "$CHOSEN" ]] && break

    for i in "${!OPTIONS[@]}"; do
        if [[ "${OPTIONS[$i]}" == "$CHOSEN" ]]; then
            INDEX="$i"
            break
        fi
    done

    case "$CHOSEN" in
        "Respect"*)
            helpers::configure::toggle_bool -v VIBRANIUM_GLOBAL_RESPECT_POWER_PROFILE
            vb-cmd-toggle-decorations
            ;;
        "Visual"*)
            helpers::configure::toggle_bool VIBRANIUM_GLOBAL_POWER_PROFILE_USE_FEEDBACK
            ;;
    esac

done
