#!/usr/bin/env bash

source vb-core-lib

INDEX=0


while true; do
    source "$VIBRANIUM_USER_SETTINGS"

    helpers::check VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL
    helpers::check VIBRANIUM_BRIGHTNESS_STEP

    OPTIONS=(
        "Use DDC protocol : $VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL"
        "Brightnes step : $VIBRANIUM_BRIGHTNESS_STEP"
    )

    mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
    CHOSEN="$(printf "%s\n" "${OPTIONS[@]}" | helpers::ui::menu "Brightness" "ESC to go back" -selected-row "$INDEX")"
    [ -z "$CHOSEN" ] && break

    for i in "${!OPTIONS[@]}"; do
        if [ "${OPTIONS[$i]}" = "$CHOSEN" ]; then
            INDEX="$i"
            break
        fi
    done

    case "$CHOSEN" in
        "Use DDC"*)
            helpers::configure::toggle_bool "VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL"
            ;;
        *"OSD"*)
            helpers::configure::toggle_bool "VIBRANIUM_BRIGHTNESS_USE_OSD"
            ;;
        "Brightnes step"*)
            helpers::configure::set_digit "Brightness step" "Brightness" \
                "int" 2 20 "VIBRANIUM_BRIGHTNESS_STEP"
            ;;
    esac
done
