#!/bin/bash

_get_rofi_theme() {
  local config="$XDG_CONFIG_HOME/rofi/config.rasi"
  local line theme

  while IFS= read -r line; do
    if [[ ! $line == *@import* ]]; then
      continue
    fi

    if [[ $line =~ @import[[:space:]]+\"[^\"]*/([^/\"]+)\.rasi\" ]]; then
      theme="${BASH_REMATCH[1]}"

      theme="${theme#theme-}"
      theme="${theme//-/ }"
      theme="${theme^}"

      printf "%s" "$theme"
      return 0
    fi
  done <"$config"

  printf "%s" "couldn't get theme"
}

_set_rofi_theme() {
  local config input themes dir

  config="$XDG_CONFIG_HOME/rofi/config.rasi"
  dir="$XDG_CONFIG_HOME/rofi/themes"

  themes=()

  for file in "$dir"/*.rasi; do
    [[ -e "$file" ]] || continue

    local name value

    value="${file##*/}"
    value="${value/.rasi/}"
    value="${value#theme-}"

    name="${value//-/ }"
    name="${name^}"

    themes+=("$name:$value")
  done

  input="$(cfgr::set_string --title "Menu Theme" \
    --option "${themes[@]}")" || return

  sed -i "s|\(@import \"./themes/\)[^\"]*|\1${input}.rasi|" "$config"
}

_build() {
  cfgr::item::bool \
    --var VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ON_START \
    --label "Launch on startup"

  cfgr::item::string \
    --var VIBRANIUM_GLOBAL_SEARCH_ENGINE \
    --label "Search engine" \
    --title "Search Engine" \
    --option "Google:google" "DuckDuckGo:duckduckgo" "Bing:bing" "Brave:brave"

  cfgr::item::bool \
    --var VIBRANIUM_GLOBAL_APP_LAUNCHER_AUTO_SELECT \
    --label "Auto select"

  cfgr::item::bool \
    --var VIBRANIUM_GLOBAL_APP_LAUNCHER_ALWAYS_FOCUS \
    --label "Focus first"

  cfgr::item::bool \
    --var VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ICONS \
    --label "Show icons"

  cfgr::item::bool \
    --var VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_WEBAPPS \
    --label "Show PWAs"

  cfgr::item::raw "Theme : $(_get_rofi_theme)" "action:_set_rofi_theme"
}

cfgr::run "App Laucher" "_build" \
  VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ON_START \
  VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_WEBAPPS \
  VIBRANIUM_GLOBAL_APP_LAUNCHER_AUTO_SELECT \
  VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ICONS \
  VIBRANIUM_GLOBAL_APP_LAUNCHER_ALWAYS_FOCUS \
  VIBRANIUM_GLOBAL_SEARCH_ENGINE
