#!/usr/bin/env bash

# ================================================================================ #

_update_timeout() {
  local index="$1"
  local seconds="$2"
  local config="$XDG_CONFIG_HOME/hypr/hypridle.conf"

  TIMEOUTS[index - 1]="$seconds"

  awk -v lock="${TIMEOUTS[0]}" -v sleep="${TIMEOUTS[1]}" \
    -f "$VIBRANIUM/awk/cfgr-idle-update-timeouts.awk" "$config" > \
    "$config.tmp" && mv "$config.tmp" "$config"
}

_set_timeouts() {
  local title="$1"
  local timer_index="$2"
  local min_minutes="$3"
  local max_minutes="$4"

  local input
  input="$(cfgr::set_digit \
    --title "$title timeout" \
    --hint "$title after N minutes" \
    --type int \
    --min "$min_minutes" \
    --max "$max_minutes")" || return

  _update_timeout "$timer_index" $((input * 60))
  systemctl --user restart hypridle &
}

# ================================================================================ #

_build() {
  local config_valid="true"
  local config="$XDG_CONFIG_HOME/hypr/hypridle.conf"

  mapfile -t TIMEOUTS < <(awk -f "$VIBRANIUM/awk/cfgr-idle-get-timeouts.awk" "$config")

  if [[ -z "${TIMEOUTS[@]}" ]]; then
    config_valid="false"
    if [[ -f "$config" ]]; then
      notify-send -r 3 -t 10000 "Unable To Parse Config File" \
        "<span foreground='${P_ACCENT}'><b>hypridle.conf</b></span> is formatted incorrectly. Timeout options are unavailable."
    fi
  fi

  if [[ "$config_valid" == "true" ]]; then
    local lock_timeout sleep_timeout

    lock_timeout="${TIMEOUTS[0]}"
    sleep_timeout="${TIMEOUTS[1]}"

    # Convert seconds to minutes for display and range clamping.
    lock_timeout="$((lock_timeout / 60))"
    sleep_timeout="$((sleep_timeout / 60))"

    cfgr::item::action \
      --func "_set_timeouts Lock 1 1 $sleep_timeout" \
      --label "Lock after : ${lock_timeout}m"

    cfgr::item::action \
      --func "_set_timeouts Sleep 2 $lock_timeout 3600" \
      --label "Sleep after : ${sleep_timeout}m"
  fi

  local inh_type="${VIBRANIUM_GLOBAL_INHIBIT_TYPE^}"
  local inh_var="VIBRANIUM_GLOBAL_INHIBIT_TYPE"

  cfgr::item::action \
    --func "cfgr::set_string --title Type --option 'Idle:idle' 'Sleep:sleep' --var $inh_var" \
    --hook "vb-toggle-inhibitor --retoggle" \
    --label "Inhibit type : $inh_type"
}

cfgr::run "Idle" "_build" VIBRANIUM_GLOBAL_INHIBIT_TYPE
