#!/bin/bash

_toggle_osd_service() {
  # Since we're working with outdated value, flip the logic
  if [[ "$VIBRANIUM_GLOBAL_USE_OSD" == true ]]; then
    systemctl -q --user disable --now swayosd &
  else
    systemctl -q --user enable --now swayosd &
  fi
}

_set_update_channel() {
  local chosen
  chosen="$(cfgr::set_string \
    --title "Update Channel" \
    --option "Release:release" "Upstream:upstream" "Dev:dev")"
  vb-dev-switch-channel "$chosen"
}

_get_update_channel() {
  local state channel
  state="$VIBRANIUM_STATE/update.channel"

  if [[ -f "$state" ]]; then
    channel="$(<"$state")"
    printf "%s" "${channel^}"
  else
    local branch
    branch="$(git -C "$VIBRANIUM" branch --show-current)"
    printf "%s" "$branch" | tee "$state"
  fi
}

_get_vb_updates (){
  local file="$XDG_CONFIG_HOME/systemd/user/default.target.wants/vibranium-update.timer"

  if [[ -L "$file" ]]; then
    return 0
  else
    return 1
  fi
}

_toggle_vb_updates (){
  if _get_vb_updates; then
    systemctl -q --user disable --now vibranium-update.timer
  else
    systemctl -q --user enable --now vibranium-update.timer
  fi
}

_build() {
  local update_channel
  update_channel="$(_get_update_channel)"

  # Don't show this option at all when
  # SwayOSD isn't installed
  if command -v swayosd-client >/dev/null; then
    cfgr::item::bool \
      --var VIBRANIUM_GLOBAL_USE_OSD \
      --label "OSD enabled" \
      --hook "_toggle_osd_service"
  fi

  if _get_vb_updates; then
    local vb_updates_enabled="true"
  else
    local vb_updates_enabled="false"
  fi

  cfgr::item::raw "Update channel : $update_channel" "action:_set_update_channel"
  cfgr::item::raw "Updates auto check : $vb_updates_enabled" "action:_toggle_vb_updates"
}

cfgr::run "General" "_build" \
  VIBRANIUM_GLOBAL_CONFIRM_TO_KILL \
  VIBRANIUM_GLOBAL_USE_OSD
