#!/usr/bin/env bash

source vb-lib-core
source vb-lib-hypr

CONFIG="$HYPR_CONF_ADVANCED"

ADVANCED_SPEC=(
  "misc:vrr|int"
  "misc:vfr|bool"
  "misc:middle_click_paste|bool"
  "render:direct_scanout|bool"
  "misc:disable_autoreload|bool"
  "general:layout|str"
  "cursor:zoom_detached_camera|bool"
)

_layout_submenu() {
  local opts chosen
  opts=("Dwindle" "Master" "Scrolling" "Monocle")

  while true; do
    mapfile -t opts < <(helpers::configure::build_menu "${opts[@]}")
    helpers::ui::menu chosen "Layout" "ESC to go back" -- "${opts[@]}"
    if [[ -z "$chosen" ]]; then
      break
    fi
    hypr::set "general:layout" "${chosen,,}" "$CONFIG"
    break
  done
}

INDEX=0

while true; do
  hypr::reload
  hypr::fetch "${ADVANCED_SPEC[@]}"

  # VRR has 3 states, map int -> display string
  vrr_display=
  case "${HYPR[misc:vrr]}" in
    0) vrr_display=false ;;
    1) vrr_display=true ;;
    *) vrr_display=fullscreen ;;
  esac

  OPTIONS=(
    "Variable refresh rate : $vrr_display"
    "Zoom detached camera : ${HYPR[cursor:zoom_detached_camera]}"
    "Variable frame rate : ${HYPR[misc:vfr]}"
    "Disable auto reload : ${HYPR[misc:disable_autoreload]}"
    "Middle click paste : ${HYPR[misc:middle_click_paste]}"
    "Direct scanout : ${HYPR[render:direct_scanout]}"
    "Layout : ${HYPR[general:layout]^}"
  )

  mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
  helpers::ui::menu CHOSEN "Advanced" "ESC to go back" -selected-row "$INDEX" -- "${OPTIONS[@]}"
  if [[ -z "$CHOSEN" ]]; then
    break
  fi
  helpers::configure::track_index OPTIONS "$CHOSEN" INDEX

  case "$CHOSEN" in
    "Layout"*)              _layout_submenu ;;
    "Zoom detached camera"*) hypr::toggle "cursor:zoom_detached_camera" "$CONFIG" ;;
    "Disable auto reload"*)  hypr::toggle "misc:disable_autoreload"     "$CONFIG" ;;
    "Middle click paste"*)   hypr::toggle "misc:middle_click_paste"     "$CONFIG" ;;
    "Variable frame rate"*)  hypr::toggle "misc:vfr"                    "$CONFIG" ;;
    "Direct scanout"*)       hypr::toggle "render:direct_scanout"       "$CONFIG" ;;
    "Variable refresh rate"*)
      while true; do
        helpers::ui::menu vrr_chosen "VRR" "ESC to go back" -- \
          "Enable" "Disable" "Fullscreen only" "<b>Help</b>"

        if [[ -z "$vrr_chosen" ]]; then
          break
        fi

        case "$vrr_chosen" in
          "Enable")          hypr::set "misc:vrr" 1 "$CONFIG"; break ;;
          "Disable")         hypr::set "misc:vrr" 0 "$CONFIG"; break ;;
          "Fullscreen only") hypr::set "misc:vrr" 2 "$CONFIG"; break ;;
          *"Help"*)          vb-cmd-show-help hyprland-vrr ;;
        esac
      done
      ;;
  esac
done
