#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

# ================================================================================ #

_get_timeouts() {
  local config="$XDG_CONFIG_HOME/hypr/hypridle.conf"
  awk -f "$VIBRANIUM/awk/cfgr-idle-get-timeouts.awk" "$config"
}

_update_timeout() {
  local index="$1"
  local seconds="$2"
  local config="$XDG_CONFIG_HOME/hypr/hypridle.conf"

  TIMEOUTS[$((index - 1))]="$seconds"

  awk -v lock="${TIMEOUTS[0]}" -v sleep="${TIMEOUTS[1]}" \
    -f "$VIBRANIUM/awk/cfgr-idle-update-timeouts.awk" "$config" > \
    "$config.tmp" && mv "$config.tmp" "$config"
}

_set_timeouts() {
  local title="$1"
  local timer_index="$2"
  local min_minutes="$3"
  local max_minutes="$4"

  local input
  input="$(cfgr::set_digit "$title timeout" int $min_minutes $max_minutes --hint "$title after N minutes")" || return

  _update_timeout "$timer_index" $((input * 60))
  systemctl --user restart hypridle &
}

# ================================================================================ #

_build() {
  mapfile -t TIMEOUTS < <(_get_timeouts)
  local lock_timeout sleep_timeout

  lock_timeout="${TIMEOUTS[0]}"
  sleep_timeout="${TIMEOUTS[1]}"

  # Convert to minutes
  lock_timeout="$((lock_timeout / 60))"
  sleep_timeout="$((sleep_timeout / 60))"

  cfgr::item::action "_set_timeouts Lock 1 1 $sleep_timeout" "Lock after : ${lock_timeout}m"
  cfgr::item::action "_set_timeouts Sleep 2 $lock_timeout 3600" "Sleep after : ${sleep_timeout}m"
  cfgr::item::action "vb-cmd-show-help idle" "Help"
}

cfgr::run "Idle" "_build"
