#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

_build() {
  cfgr::item::string VIBRANIUM_SCREENSHOT_FILE_TYPE "Filetype" "Filetype" "PNG:png" "JPEG:jpeg" "PPM:ppm"

  if [[ "$VIBRANIUM_SCREENSHOT_FILE_TYPE" == "jpeg" ]]; then
    cfgr::item::digit VIBRANIUM_SCREENSHOT_JPEG_QUALITY "JPEG quality" "Quality (int)" "JPEG Quality" int 1 100
  fi

  if [[ "$(hyprctl getoption animations:enabled)" =~ 1 ]]; then
    cfgr::item::bool VIBRANIUM_SCREENSHOT_FLASH_SCREEN "Flash screen"
    cfgr::item::bool VIBRANIUM_SCREENSHOT_FLASH_BORDER "Flash border"
  fi

  cfgr::item::bool VIBRANIUM_SCREENSHOT_SAVE_TO_DISK "Save to disk"
  cfgr::item::bool VIBRANIUM_SCREENSHOT_SHOW_NOTIFICATION "Show notification"
}

cfgr::run "Screenshots" "_build" \
  VIBRANIUM_SCREENSHOT_FILE_TYPE \
  VIBRANIUM_SCREENSHOT_JPEG_QUALITY \
  VIBRANIUM_SCREENSHOT_FLASH_BORDER \
  VIBRANIUM_SCREENSHOT_FLASH_SCREEN \
  VIBRANIUM_SCREENSHOT_SAVE_TO_DISK \
  VIBRANIUM_SCREENSHOT_SHOW_NOTIFICATION
