#!/usr/bin/env bash

source vb-core-lib

_edit_roundness() {
  local input
  local dunstrc
  local config_rasi
  local swayosd_css

  input=$(helpers::configure::set_digit --verify "Border roundness" "Border roundness" "int" 0 16)
  [[ -z "$input" ]] && return
  vb-cmd-edit-wm-config "decoration:rounding:$input" "$HYPR_CONFIG"

  dunstrc="$XDG_CONFIG_HOME/dunst/dunstrc"
  sed -i "/corner_radius/s/=.*/= $input/" "$dunstrc"
  vb-cmd-refresh-dunst &

  config_rasi="$XDG_CONFIG_HOME/rofi/config.rasi"
  sed -i "/border-radius/s/: .*/: ${input}px;/" "$config_rasi"

  swayosd_css="$XDG_CONFIG_HOME/swayosd/style.css"
  sed -i "/border-radius/s/: .*/: ${input}px;/" "$swayosd_css"

  helpers::check VIBRANIUM_GLOBAL_USE_OSD
  if [[ "$VIBRANIUM_GLOBAL_USE_OSD" == true ]]; then
    systemctl --user restart swayosd &
  fi
}

_set_animations_preset() {
  local folder target anim_opts anim_chosen

  folder="$VIBRANIUM/default/hypr/animations"
  target="$HOME/.config/hypr/hyprland.conf.d/animations.conf"

  anim_opts=("$folder"/*.conf)
  anim_opts=("${anim_opts[@]##*/}")   # strip leading path
  anim_opts=("${anim_opts[@]%.conf}") # strip extension
  anim_opts=("${anim_opts[@]^}")

  while true; do
    helpers::ui::menu anim_chosen "Animations" "ESC to go back" -- "${anim_opts[@]}"
    [[ -z "$anim_chosen" ]] && break

    ln -sf "$folder/${anim_chosen,}.conf" "$target"

    hyprctl -q reload config-only
    break
  done
}

_edit_bool() {
  case "$(hyprctl -j getoption "$1" | jq -r '.int')" in
    1) vb-cmd-edit-wm-config "${1}:false" "$HYPR_CONFIG" ;;
    0) vb-cmd-edit-wm-config "${1}:true" "$HYPR_CONFIG" ;;
  esac
  hyprctl -q reload config-only
}

_blur_submenu() {
  local parameters index opts input
  local labels

  while true; do
    mapfile -t parameters < <(
      hyprctl -j --batch \
        "getoption decoration:blur:enabled;
             getoption decoration:blur:size;
             getoption decoration:blur:passes;
             getoption decoration:blur:contrast;
             getoption decoration:blur:brightness;
             getoption decoration:blur:vibrancy;
             getoption decoration:blur:noise
             " | jq -sr '.[] | .option as $o |
                if ($o | test("enabled")) then
                    (if .int == 1 then "true" else "false" end)
                elif ($o | test("passes|size")) then
                    .int
                else
                    .float
                end
            '
    )

    read -r enabled size passes contrast brightness vibrancy noise <<<"${parameters[*]}"

    # Temporary removed
    # helpers::check VIBRANIUM_GLOBAL_RESPECT_POWER_PROFILE
    # local respect_power_profile="$VIBRANIUM_GLOBAL_RESPECT_POWER_PROFILE"
    # local power_profile="$(vb-cmd-get-power)"

    labels=("Enabled : $enabled")

    if [[ "$enabled" == true ]]; then
      labels+=(
        "Size : $size"
        "Noise : $noise"
        "Passes : $passes"
        "Vibrancy : $vibrancy"
        "Contrast : $contrast"
        "Brightness : $brightness"
      )
    fi

    mapfile -t labels < <(helpers::configure::build_menu "${labels[@]}")
    helpers::ui::menu chosen "Blur" "ESC to go back" -selected-row "$index" -- "${labels[@]}"
    [[ -z $chosen ]] && break

    for i in "${!labels[@]}"; do
      [[ "${labels[$i]}" == "$chosen" ]] && {
        index="$i"
        break
      }
    done

    case "$chosen" in
      "Enabled"*)
        _edit_bool "decoration:blur:enabled"

        case "$enabled" in
          "true")
            sed -i '/blur_size/s/ =.*/ = 1/' "$HYPRLOCK_CONFIG"
            sed -i '/blur_passes/s/ =.*/ = 1/' "$HYPRLOCK_CONFIG"
            ;;
          "false")
            sed -i '/blur_size/s/ =.*/ = 5/' "$HYPRLOCK_CONFIG"
            sed -i '/blur_passes/s/ =.*/ = 3/' "$HYPRLOCK_CONFIG"
            ;;
        esac

        ;;
      "Noise"*)
        input=$(helpers::configure::set_digit --verify "Blur noise" "Blur noise" "float" 0.0 1.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:blur:noise:$input" "$HYPR_CONFIG"
        ;;
      "Vibrancy"*)
        input=$(helpers::configure::set_digit --verify "Blur vibrancy" "Blur vibrancy" "float" 0.0 1.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:blur:vibrancy:$input" "$HYPR_CONFIG"
        ;;
      "Brightness"*)
        input=$(helpers::configure::set_digit --verify "Blur brightness" "Blur brightness" "float" 0.0 2.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:blur:brightness:$input" "$HYPR_CONFIG"
        ;;
      "Contrast"*)
        input=$(helpers::configure::set_digit --verify "Blur contrast" "Blur contrast" "float" 0.0 2.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:blur:contrast:$input" "$HYPR_CONFIG"
        ;;
      "Size"*)
        input=$(helpers::configure::set_digit --verify "Blur size" "Blur size" "int" 1 512)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:blur:size:$input" "$HYPR_CONFIG"
        ;;
      "Passes"*)
        input=$(helpers::configure::set_digit --verify "Blur passes" "Blur passes" "int" 1 20)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:blur:passes:$input" "$HYPR_CONFIG"
        ;;
    esac

    hyprctl -q reload config-only
  done
}

_shadow_submenu() {
  local parameters index opts input
  local labels

  while true; do
    mapfile -t parameters < <(
      hyprctl -j --batch \
        "getoption decoration:shadow:enabled;
             getoption decoration:shadow:render_power;
             getoption decoration:shadow:range;
             getoption decoration:shadow:sharp;
             getoption decoration:shadow:ignore_window
             " | jq -sr '.[] | .option as $o |
                if ($o | test("enabled|sharp")) then
                    (if .int == 1 then "true" else "false" end)
                elif ($o | test("ignore_window")) then
                    (if .int == 1 then "false" else "true" end)
                else
                    .int
                end
            '
    )

    read -r enabled render_power range sharp ignore_window <<<"${parameters[*]}"

    # Temporary removed
    # helpers::check VIBRANIUM_GLOBAL_RESPECT_POWER_PROFILE
    # local respect_power_profile="$VIBRANIUM_GLOBAL_RESPECT_POWER_PROFILE"
    # local power_profile="$(vb-cmd-get-power)"

    labels=("Enabled : $enabled")

    if [[ "$enabled" == true ]]; then
      labels+=(
        "Power : $render_power"
        "Range : ${range}px"
        "Sharp : $sharp"
        "Behind the window : $ignore_window"
      )
    fi

    mapfile -t labels < <(helpers::configure::build_menu "${labels[@]}")
    helpers::ui::menu chosen "Shadows" "ESC to go back" -selected-row "$index" -- "${labels[@]}"
    [[ -z $chosen ]] && break

    for i in "${!labels[@]}"; do
      [[ "${labels[$i]}" == "$chosen" ]] && {
        index="$i"
        break
      }
    done

    case "$chosen" in
      "Enabled"*) _edit_bool "decoration:shadow:enabled" ;;
      "Sharp"*) _edit_bool "decoration:shadow:sharp" ;;
      "Behind"*) _edit_bool "decoration:shadow:ignore_window" ;;
      "Power"*)
        input=$(helpers::configure::set_digit --verify "Render power" "Render power" "int" 1 4)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:shadow:render_power:$input" "$HYPR_CONFIG"
        ;;
      "Range"*)
        if [[ "$sharp" == true ]]; then
          input=$(helpers::configure::set_digit --verify "Shadow range" "Shadow range" "int" 1 128)
        else
          input=$(helpers::configure::set_digit --verify "Shadow range" "Shadow range" "int" 4 128)
        fi
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:shadow:range:$input" "$HYPR_CONFIG"
        ;;
    esac

    hyprctl -q reload config-only
  done
}

_decoration_submenu() {
  local parameters index opts input
  local labels

  while true; do
    mapfile -t parameters < <(
      hyprctl -j --batch \
        "getoption general:border_size;
             getoption decoration:rounding;
             getoption decoration:rounding_power;
             getoption decoration:active_opacity;
             getoption decoration:inactive_opacity;
             getoption decoration:fullscreen_opacity;
             getoption decoration:dim_inactive;
             getoption decoration:dim_strength;
             getoption decoration:dim_modal;
             getoption decoration:dim_special;
             getoption decoration:border_part_of_window
             " | jq -sr '.[] | .option as $o |
                if ($o | test("dim_(inactive|modal)|border_part_of_window"; "i")) then
                    (if .int == 1 then "true" else "false" end)
                elif ($o | test(".*_(opacity|power|strength|special)")) then
                    (.float * 100 | round / 100)
                else
                    .int
                end
            '
    )

    read -r bordersize rounding round_power a_opacity i_opacity f_opacity \
      dim_inactive dim_strength dim_modal dim_special border_part <<<"${parameters[*]}"

    labels=(
      "Border size : $bordersize"
      "Border roundness : $rounding"
      "Rounding power : $round_power"
      "Active window opacity : $a_opacity"
      "Inactive window opacity : $i_opacity"
      "Fullscreen window opacity : $f_opacity"
      "Dim inactive window : $dim_inactive"
    )

    [[ "$dim_inactive" == true ]] ||
      [[ "$dim_specialdim_modal" == true ]] && {
      labels+=(
        "Dim strength : $dim_strength"
      )
    }

    labels+=(
      "Dim modal windows : $dim_modal"
      "Dim special workspace : $dim_special"
      "Border part of window : $border_part"
    )

    mapfile -t labels < <(helpers::configure::build_menu "${labels[@]}")
    helpers::ui::menu chosen "Decoration" "ESC to go back" -selected-row "$index" -- "${labels[@]}"
    [[ -z $chosen ]] && break

    for i in "${!labels[@]}"; do
      [[ "${labels[$i]}" == "$chosen" ]] && {
        index="$i"
        break
      }
    done

    case "$chosen" in
      "Border size"*)
        input=$(helpers::configure::set_digit --verify "Border size" "Border size" "int" 0 24)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "general:border_size:$input" "$HYPR_CONFIG"
        ;;
      "Border roundness"*) _edit_roundness ;;
      "Rounding power"*)
        input=$(helpers::configure::set_digit --verify "Rounding power" "Rounding power" "float" 1.0 10.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:rounding_power:$input" "$HYPR_CONFIG"
        ;;
      "Active window opacity"*)
        input=$(helpers::configure::set_digit --verify "Active opacity" "Active opacity" "float" 0.0 1.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:active_opacity:$input" "$HYPR_CONFIG"
        ;;
      "Inactive window opacity"*)
        input=$(helpers::configure::set_digit --verify "Inactive opacity" "Inactive opacity" "float" 0.0 1.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:inactive_opacity:$input" "$HYPR_CONFIG"
        ;;
      "Fullscreen window opacity"*)
        input=$(helpers::configure::set_digit --verify "Fullscreen opacity" "Fullscreen opacity" "float" 0.0 1.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:fullscreen_opacity:$input" "$HYPR_CONFIG"
        ;;
      "Dim inactive window"*) _edit_bool "decoration:dim_inactive" ;;
      "Dim modal windows"*) _edit_bool "decoration:dim_modal" ;;
      "Dim special workspace"*)
        input=$(helpers::configure::set_digit --verify "Dim special" "Dim special" "float" 0.0 1.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:dim_special:$input" "$HYPR_CONFIG"
        ;;
      "Dim strength"*)
        input=$(helpers::configure::set_digit --verify "Dim strength" "Dim strength" "float" 0.0 1.0)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "decoration:dim_strength:$input" "$HYPR_CONFIG"
        ;;
      "Border part of window"*) _edit_bool "decoration:border_part_of_window" ;;
    esac

    hyprctl -q reload config-only
  done
}

_animations_submenu() {
  local opts chosen
  local enabled anim_file anim_preset

  anim_file="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.conf.d/animations.conf"

  while true; do
    enabled="$(hyprctl -j getoption animations:enabled | jq -r '.int')"

    anim_preset="$(readlink "$anim_file")"
    anim_preset="${anim_preset##*/}"   # strip path
    anim_preset="${anim_preset%.conf}" # strip extension

    [[ "$enabled" == "1" ]] && enabled="true" || enabled="false"

    opts=("Enabled : $enabled")

    if [[ "$enabled" == true ]]; then
      opts+=("Preset : ${anim_preset^}")
    fi

    mapfile -t opts < <(helpers::configure::build_menu "${opts[@]}")

    helpers::ui::menu chosen "Animations" "ESC to go back" -- "${opts[@]}"
    [[ -z $chosen ]] && break

    case "$chosen" in
      "Enabled"*) vb-cmd-toggle-animations --quiet ;;
      "Preset"*) _set_animations_preset ;;
    esac
  done
}

_gaps_submenu() {
  local index parameters opts chosen smartgaps_enabled input

  while true; do
    [[ -f "$SMART_GAPS_CONFIG" ]] && {
      smartgaps_enabled="true"
    } || {
      smartgaps_enabled="false"
    }

    mapfile -t parameters < <(
      hyprctl -j --batch \
        "getoption general:gaps_in;
                 getoption general:gaps_out
                " | jq -r '.custom | split(" ")[0]'
    )

    read -r gaps_in gaps_out <<<"${parameters[*]}"

    opts=(
      "Inner gaps : $gaps_in"
      "Outer gaps : $gaps_out"
    )

    ((gaps_in != 0 && gaps_out != 0)) && {
      opts+=("Smart gaps : $smartgaps_enabled")
    }

    mapfile -t opts < <(helpers::configure::build_menu "${opts[@]}")
    helpers::ui::menu chosen "Gaps" "ESC to go back" -selected-row "$index" -- "${opts[@]}"
    [[ -z $chosen ]] && break

    for i in "${!opts[@]}"; do
      [[ "${opts[$i]}" == "$chosen" ]] && {
        index="$i"
        break
      }
    done

    case "$chosen" in
      "Inner gaps"*)
        input=$(helpers::configure::set_digit --verify "Inner gaps" "Inner gaps" "int" 0 50)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "general:gaps_in:$input" "$HYPR_CONFIG"
        ;;
      "Outer gaps"*)
        input=$(helpers::configure::set_digit --verify "Outer gaps" "Outer gaps" "int" 0 50)
        [[ -n "$input" ]] && vb-cmd-edit-wm-config "general:gaps_out:$input" "$HYPR_CONFIG"
        ;;
      "Smart gaps"*) vb-cmd-toggle-smart-gaps ;;
    esac

    hyprctl -q reload config-only
  done
}

INDEX=0
SMART_GAPS_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.conf.d/smart-gaps.conf"
HYPR_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.conf.d/look-and-feel.conf"
HYPRLOCK_CONFIG="$XDG_CONFIG_HOME/hypr/hyprlock.conf"

while true; do
  OPTIONS=(
    "<b>Blur</b>"
    "<b>Gaps</b>"
    "<b>Shadows</b>"
    "<b>Decoration</b>"
    "<b>Animations</b>"
  )

  mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
  helpers::ui::menu CHOSEN "Look & Feel" "ESC to go back" -selected-row "$INDEX" -- "${OPTIONS[@]}"
  [[ -z $CHOSEN ]] && break

  for i in "${!OPTIONS[@]}"; do
    if [ "${OPTIONS[$i]}" = "$CHOSEN" ]; then
      INDEX="$i"
      break
    fi
  done

  case "$CHOSEN" in
    *"Blur"*)
      _blur_submenu
      ;;
    *"Shadows"*)
      _shadow_submenu
      ;;
    *"Decoration"*)
      _decoration_submenu
      ;;
    *"Animations"*)
      _animations_submenu
      ;;
    *"Gaps"*)
      _gaps_submenu
      ;;
  esac
done
