#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

_build() {
  cfgr::item::bool \
    --var VIBRANIUM_GLOBAL_SHOW_NOW_PLAYING \
    --label "Show now playing notification"

  if [[ "$VIBRANIUM_GLOBAL_SHOW_NOW_PLAYING" == true ]]; then
    cfgr::item::bool \
      --var VIBRANIUM_GLOBAL_NOW_PLAYING_SHOW_ALBUM_ART \
      --label "Show album art"
  fi

  cfgr::item::action --func "vb-cmd-show-help now-playing" --label "Help"
}

cfgr::run "Now Playing" "_build" \
  VIBRANIUM_GLOBAL_SHOW_NOW_PLAYING \
  VIBRANIUM_GLOBAL_NOW_PLAYING_SHOW_ALBUM_ART
