#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

_advanced_menu() {
  _a_build() {
    cfgr::item::string \
      --var VIBRANIUM_RECORDING_VIDEO_CODEC \
      --label "Video codec" --title "Codec" \
      --option "Auto:auto" "H264:h264" "HEVC:hevc" "AV1:av1" \
               "VP8:vp8" "VP9:vp9" "HEVC (HDR):hevc_hdr" \
               "AV1 (HDR):av1_hdr" "HEVC (10 bit color):hevc_10bit" \
               "AV1 (10 bit color):av1_10bit"

    cfgr::item::string \
      --var VIBRANIUM_RECORDING_FRAMERATE_MODE \
      --label "Framerate mode" --title "Mode" \
      --option "Constant Frame Rate:cfr" "Variable Frame Rate:vfr"
    cfgr::item::string \
      --var VIBRANIUM_RECORDING_CONTAINER_TYPE \
      --label "Container type" --title "Filetype" \
      --option "mp4" "webm" "mkv"
    cfgr::item::bool \
      --var VIBRANIUM_RECORDING_FLASH_SCREEN \
      --label "Flash screen"
  }

  cfgr::run "Advanced" "_a_build" \
    VIBRANIUM_RECORDING_FRAMERATE_MODE \
    VIBRANIUM_RECORDING_CONTAINER_TYPE \
    VIBRANIUM_RECORDING_FLASH_SCREEN \
    VIBRANIUM_RECORDING_VIDEO_CODEC
}

_build() {
  cfgr::item::digit \
    --var VIBRANIUM_RECORDING_FPS \
    --label "FPS to record with" \
    --prompt "FPS (int)" \
    --title "FPS" \
    --type int \
    --min 15 \
    --max 120

  cfgr::item::string \
    --var VIBRANIUM_RECORDING_QUALITY \
    --label "Recording quality" \
    --title "Quality" \
    --option "Medium:medium" "High:high" \
              "Very High:very_high" "Ultra:ultra"

  cfgr::item::bool \
    --var VIBRANIUM_RECORDING_CAPTURE_SINK  \
    --label "Capture output"

  cfgr::item::bool \
    --var VIBRANIUM_RECORDING_CAPTURE_SOURCE \
    --label "Capture input"

  cfgr::item::action \
    --func "_advanced_menu" \
    --label "Advanced"
}

cfgr::run "Recording" "_build" \
  VIBRANIUM_RECORDING_FPS \
  VIBRANIUM_RECORDING_QUALITY \
  VIBRANIUM_RECORDING_CAPTURE_SINK \
  VIBRANIUM_RECORDING_CAPTURE_SOURCE
