#!/usr/bin/env bash

source vb-lib-core

_set_timeouts() {
  local title="$1"
  local timer_index="$2"
  local min_minutes="$3"
  local max_minutes="$4"

  local input
  input=$(helpers::configure::set_digit --verify \
    "$title timeout" "$title" "int" "$min_minutes" "$max_minutes") || return

  _update_timeout "$timer_index" $((input * 60))
  systemctl --user restart hypridle &
}

_get_timeouts() {
  local config="$XDG_CONFIG_HOME/hypr/hypridle.conf"
  awk -f "$VIBRANIUM/awk/cfgr-idle-get-timeouts.awk" "$config"
}

_update_timeout() {
  local index="$1"
  local seconds="$2"
  local config="$XDG_CONFIG_HOME/hypr/hypridle.conf"

  local timeouts
  mapfile -t timeouts < <(_get_timeouts)
  timeouts[$((index - 1))]="$seconds"

  awk -v lock="${timeouts[0]}" -v sleep="${timeouts[1]}" \
    -f "$VIBRANIUM/awk/cfgr-idle-update-timeouts.awk" "$config" > "$config.tmp" \
    && mv "$config.tmp" "$config"
}

INDEX=0

while true; do
  source "$VIBRANIUM_USER_SETTINGS"

  mapfile -t TIMEOUTS < <(_get_timeouts)

  LOCK_TIMEOUT="${TIMEOUTS[0]}"
  SLEEP_TIMEOUT="${TIMEOUTS[1]}"

  helpers::check VIBRANIUM_GLOBAL_INHIBIT_TYPE
  INHIBIT_TYPE="$VIBRANIUM_GLOBAL_INHIBIT_TYPE"

  OPTIONS=(
    "Lock  after : $((LOCK_TIMEOUT / 60)) min"
    "Sleep after : $((SLEEP_TIMEOUT / 60)) min"
    "Inhibit type : $INHIBIT_TYPE"
    "<b>Help</b>"
  )

  mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
  helpers::ui::menu CHOSEN "Idle" "ESC to go back" -selected-row "$INDEX" -- "${OPTIONS[@]}"
  helpers::configure::track_index OPTIONS "$CHOSEN" INDEX

  case "$CHOSEN" in
    *"Inhibit"*)
      helpers::configure::set_string VIBRANIUM_GLOBAL_INHIBIT_TYPE "Sleep type" idle sleep
      (
        pid="$(systemd-inhibit --no-pager | awk '/Vibranium/ {print $4}')"

        if [[ ! -z "$pid" ]]; then
          # Disable active
          vb-cmd-toggle-inhibit
          # Start new with the new value
          vb-cmd-toggle-inhibit
        fi
      ) &
      ;;
    "Lock"*)  _set_timeouts "Lock"  1 1 $((SLEEP_TIMEOUT / 60 - 1)) ;;
    "Sleep"*) _set_timeouts "Sleep" 2 $((LOCK_TIMEOUT / 60 + 1)) 3600 ;; # 1 hour
    *"Help"*) vb-cmd-show-help idle ;;
    "") break ;;
  esac
done
