#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

_build() {
  cfgr::item::bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ON_START "Launch on startup"
  cfgr::item::bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_AI "Show AI webapps"
  cfgr::item::bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_WEBAPPS "Show webapps"
  cfgr::item::bool VIBRANIUM_GLOBAL_APP_LAUNCHER_SHOW_ICONS "Show icons"
  cfgr::item::bool VIBRANIUM_GLOBAL_APP_LAUNCHER_AUTO_SELECT "Auto select"

  cfgr::item::string VIBRANIUM_GLOBAL_SEARCH_ENGINE "Search engine" "Search Engine" \
    "Google:google" "DuckDuckGo:duckduckgo" "Bing:bing" "Brave:brave"
}

cfgr::run "App Laucher" "_build"
