#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

_build() {
  cfgr::item::bool VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL "Use DDC protocol"
  cfgr::item::bool VIBRANIUM_BRIGHTNESS_NOTIFY "Show notificaation"
  cfgr::item::digit VIBRANIUM_BRIGHTNESS_STEP "Brightnes step" "Step" "Brightness" int 1 25
}

cfgr::run "Brightness" "_build" \
  VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL \
  VIBRANIUM_BRIGHTNESS_NOTIFY \
  VIBRANIUM_BRIGHTNESS_STEP
