#!/usr/bin/env bash

source vb-core-lib

WAYBAR_CFG="$XDG_CONFIG_HOME/waybar/config.jsonc"

_check_module() {
    local module="$1"
    if grep -Eq "^\s*//.*\"$module\"" "$WAYBAR_CFG"; then
        return 0 # commented out - module disabled
    else
        return 1
    fi
}

_toggle_module() {
    local module="$1"
    if _check_module "$module"; then
        sed -i "s|^\(\s*\)//\s*\(.*\"$module\".*\)|\1\2|" "$WAYBAR_CFG"
    else
        sed -i "s|^\(\s*\)\(\".*$module\".*\)|\1// \2|" "$WAYBAR_CFG"
    fi
    systemctl --user restart waybar
}

_power_profile_notify() {
    if [ "$(vb-cmd-get-option VIBRANIUM_BAR_POWER_PROFILE_MODULE_ENABLE)" = "true" ] && [ "$(vb-cmd-get-power)" = "balanced" ]; then
        msg="\n<span foreground='${P_GREEN}'><b>•</b></span> <span foreground='${P_PURPLE}'><b>Don't be confused! The module you just enabled is active, actually</b></span>\n\n"
        msg+="It isn’t shown in the bar because you’re on the '<span foreground='${P_YELLOW}'><b>balanced</b></span>' power\nprofile, which is the default one and doesn’t need to be displayed.\n"
        msg+="\n<span foreground='${P_GREEN}'><b>•</b></span> <span foreground='${P_YELLOW}'><b>Try switching your power profile to see it in action</b></span>"
        notify-send -r 1 -t 18000 "Vibranium" "$msg"
    fi
}

INDEX=0


while true; do
    source "$VIBRANIUM_USER_SETTINGS"

    helpers::check VIBRANIUM_BAR_COLOR_PICKER_MODULE_ENABLE
    helpers::check VIBRANIUM_BAR_POWER_PROFILE_MODULE_ENABLE
    helpers::check VIBRANIUM_BAR_NIGHT_LIGHT_MOUDLE_ENABLE
    helpers::check VIBRANIUM_BAR_WEATHER_MODULE_ENABLE
    helpers::check VIBRANIUM_BAR_PACMAN_MODULE_ENABLE

    if _check_module 'hyprland/language'; then
        KEYBOARD_LAYOUT_ENABLED="false"
    else
        KEYBOARD_LAYOUT_ENABLED="true"
    fi

    if _check_module 'network'; then
        NETWORK_ENABLED="false"
    else
        NETWORK_ENABLED="true"
    fi

    if _check_module 'pulseaudio#microphone'; then
        MICROPHONE_ENABLED="false"
    else
        MICROPHONE_ENABLED="true"
    fi

    if _check_module 'pulseaudio#volume'; then
        VOLUME_ENABLED="false"
    else
        VOLUME_ENABLED="true"
    fi

    if _check_module 'bluetooth'; then
        BLUETOOTH_ENABLED="false"
    else
        BLUETOOTH_ENABLED="true"
    fi

    OPTIONS=(
        "Keyboard layout : $KEYBOARD_LAYOUT_ENABLED"
        "Power profile : $VIBRANIUM_BAR_POWER_PROFILE_MODULE_ENABLE"
        "Color picker : $VIBRANIUM_BAR_COLOR_PICKER_MODULE_ENABLE"
        "Night light : $VIBRANIUM_BAR_NIGHT_LIGHT_MOUDLE_ENABLE"
        "Microphone : $MICROPHONE_ENABLED"
        "Bluetooth : $BLUETOOTH_ENABLED"
        "Weather : $VIBRANIUM_BAR_WEATHER_MODULE_ENABLE"
        "Network : $NETWORK_ENABLED"
        "Updates : $VIBRANIUM_BAR_PACMAN_MODULE_ENABLE"
        "Volume : $VOLUME_ENABLED"
    )

    mapfile -t OPTIONS < <(helpers::configure::build_menu "${OPTIONS[@]}")
    CHOSEN="$(printf "%s\n" "${OPTIONS[@]}" | helpers::ui::menu "Toggle modules" "ESC to go back" -selected-row "$INDEX")"
    [ -z "$CHOSEN" ] && break

    for i in "${!OPTIONS[@]}"; do
        if [ "${OPTIONS[$i]}" = "$CHOSEN" ]; then
            INDEX="$i"
            break
        fi
    done

    case "$CHOSEN" in
        "Bluetooth"*)
            _toggle_module 'bluetooth'
            ;;
        "Network"*)
            _toggle_module 'network'
            ;;
        "Microphone"*)
            _toggle_module 'pulseaudio#microphone'
            ;;
        "Volume"*)
            _toggle_module 'pulseaudio#volume'
            ;;
        "Keyboard layout"*)
            _toggle_module 'hyprland/language'
            ;;
        "Night light"*)
            helpers::configure::toggle_bool "VIBRANIUM_BAR_NIGHT_LIGHT_MOUDLE_ENABLE"
            vb-cmd-refresh-bar-module nightshift
            ;;
        "Color picker"*)
            helpers::configure::toggle_bool "VIBRANIUM_BAR_COLOR_PICKER_MODULE_ENABLE"
            vb-cmd-refresh-bar-module color-picker
            ;;
        "Power profile"*)
            helpers::configure::toggle_bool "VIBRANIUM_BAR_POWER_PROFILE_MODULE_ENABLE"
            vb-cmd-refresh-bar-module power-profile
            ;;
        "Updates"*)
            helpers::configure::toggle_bool "VIBRANIUM_BAR_PACMAN_MODULE_ENABLE"

            # Remove any existing PID marker to allow the loading animation
            # to restart. This is necessary when modules are toggled while
            # reusing the same Waybar PID.
            rm -f "$VIBRANIUM_RUNTIME"/bar_updates.*

            vb-cmd-refresh-bar-module pacman
            ;;
        "Weather"*)
            helpers::configure::toggle_bool "VIBRANIUM_BAR_WEATHER_MODULE_ENABLE"

            # Remove any existing PID marker to allow the loading animation
            # to restart. This is necessary when modules are toggled while
            # reusing the same Waybar PID.
            rm -f "$VIBRANIUM_RUNTIME"/bar_weather.*

            vb-cmd-refresh-bar-module weather
            ;;
    esac
done
