#!/usr/bin/env bash

source vb-lib-core
source vb-lib-cfgr

WAYBAR_CFG="$XDG_CONFIG_HOME/waybar/config.jsonc"
_CFG_CONTENT=""

_load_cfg() {
  _CFG_CONTENT=$(<"$WAYBAR_CFG")
}

_check_module() {
  local module="$1"
  [[ $'\n'"$_CFG_CONTENT" =~ $'\n'[[:space:]]*//[^$'\n']*\"$module\" ]]
}

_toggle_module() {
  local module="$1"
  if _check_module "$module"; then
    sed -i "s|^\(\s*\)//\s*\(.*\"$module\".*\)|\1\2|" "$WAYBAR_CFG"
  else
    sed -i "s|^\(\s*\)\(\".*$module\".*\)|\1// \2|" "$WAYBAR_CFG"
  fi

  _load_cfg
  systemctl --user restart waybar
}

_build() {
  _load_cfg

  if _check_module 'hyprland/language'; then
    KEYBOARD_LAYOUT_ENABLED="false"
  else
    KEYBOARD_LAYOUT_ENABLED="true"
  fi

  if _check_module 'network'; then
    NETWORK_ENABLED="false"
  else
    NETWORK_ENABLED="true"
  fi

  if _check_module 'pulseaudio#microphone'; then
    MICROPHONE_ENABLED="false"
  else
    MICROPHONE_ENABLED="true"
  fi

  if _check_module 'pulseaudio#volume'; then
    VOLUME_ENABLED="false"
  else
    VOLUME_ENABLED="true"
  fi

  if _check_module 'bluetooth'; then
    BLUETOOTH_ENABLED="false"
  else
    BLUETOOTH_ENABLED="true"
  fi

  cfgr::item::raw "Keyboard layout : $KEYBOARD_LAYOUT_ENABLED" "action:_toggle_module 'hyprland/language'"

  cfgr::item::bool \
    --var   VIBRANIUM_BAR_POWER_PROFILE_MODULE_ENABLE \
    --label "Power profile" \
    --hook  "vb-cmd-refresh-bar-module power-profile"

  cfgr::item::bool \
    --var   VIBRANIUM_BAR_COLOR_PICKER_MODULE_ENABLE \
    --label "Color picker" \
    --hook  "vb-cmd-refresh-bar-module color-picker"

  cfgr::item::bool \
    --var   VIBRANIUM_BAR_NIGHT_LIGHT_MODULE_ENABLE \
    --label "Night light" \
    --hook  "vb-cmd-refresh-bar-module nightshift"

  cfgr::item::raw "Microphone : $MICROPHONE_ENABLED" "action:_toggle_module 'pulseaudio#microphone'"
  cfgr::item::raw "Bluetooth : $BLUETOOTH_ENABLED"   "action:_toggle_module 'bluetooth'"

  cfgr::item::bool \
    --var   VIBRANIUM_BAR_WEATHER_MODULE_ENABLE \
    --label "Weather" \
    --hook  "vb-cmd-refresh-bar-module weather"

  cfgr::item::raw "Network : $NETWORK_ENABLED" "action:_toggle_module 'network'"

  cfgr::item::bool \
    --var   VIBRANIUM_BAR_PACMAN_MODULE_ENABLE \
    --label "Updates" \
    --hook  "vb-cmd-refresh-bar-module pacman"

  cfgr::item::raw "Volume : $VOLUME_ENABLED" "action:_toggle_module pulseaudio#volume"
}

cfgr::run "Waybar Modules" "_build" \
  VIBRANIUM_BAR_NIGHT_LIGHT_MOUDLE_ENABLE \
  VIBRANIUM_BAR_WEATHER_MODULE_ENABLE \
  VIBRANIUM_BAR_NIGHT_LIGHT_MOUDLE_ENABLE \
  VIBRANIUM_BAR_COLOR_PICKER_MODULE_ENABLE \
  VIBRANIUM_BAR_POWER_PROFILE_MODULE_ENABLE
