black_dim = "#002129"
black = "#002934"
black_bright = "#00313e"

red_dim = "#57100f"
red = "#b7221e"
red_bright = "#dc322f"

pink_dim = "#25285b"
pink = "#494fb6"
pink_bright = "#6c71c4"

green_dim = "#2c3300"
green = "#596600"
green_bright = "#859901"

yellow_dim = "#332700"
yellow = "#664d00"
yellow_bright = "#b58900"

orange_dim = "#5c2309"
orange = "#a13d11"
orange_bright = "#cb4a15"

blue_dim = "#113956"
blue = "#1a6497"
blue_bright = "#278bd2"

purple_dim = "#25285b"
purple = "#494fb6"
purple_bright = "#6c71c4"

cyan_dim = "#113b3d"
cyan = "#196265"
cyan_bright = "#2aa198"

white_dim = "#82c4d1"
white = "#90cad7"
white_bright = "#a1d2dd"

gray_dim = "#00657f"
gray = "#007694"
gray_bright = "#0087aa"

accent_dim = "#113b3d"
accent = "#196265"
accent_bright = "#2aa198"

background_h = "#001014"
background_0 = "#001419"
background_1 = "#00313e"
background_2 = "#004253"
background_3 = "#005368"
background_4 = "#00637c"
background_5 = "#007491"

foreground_h = "#dff0f3"
foreground_0 = "#c0e1e8"
foreground_1 = "#a1d3dd"
foreground_2 = "#91cbd7"
foreground_3 = "#72bdcc"
foreground_4 = "#52aec1"
