black_dim = "#2b2c32"
black = "#393b44"
black_bright = "#4a4d59"

red_dim = "#c33c5e"
red = "#c94f6d"
red_bright = "#d67186"

pink_dim = "#975894"
pink = "#d67ad2"
pink_bright = "#e39fdf"

green_dim = "#5d7e6e"
green = "#81b29a"
green_bright = "#aecebe"

yellow_dim = "#af9a5e"
yellow = "#dbc074"
yellow_bright = "#e6d199"

orange_dim = "#c3824f"
orange = "#f4a261"
orange_bright = "#fbbb8b"

blue_dim = "#526f97"
blue = "#719cd6"
blue_bright = "#8dadde"

purple_dim = "#705797"
purple = "#9d79d6"
purple_bright = "#b99ce2"

cyan_dim = "#4a9092"
cyan = "#63cdcf"
cyan_bright = "#94dbdc"

white_dim = "#b2b2b3"
white = "#dfdfe0"
white_bright = "#e8e8e8"

gray_dim = "#535c67"
gray = "#738091"
gray_bright = "#98a1ae"

accent_dim = "#526f97"
accent = "#719cd6"
accent_bright = "#8dadde"

background_h = "#131a24"
background_0 = "#192330"
background_1 = "#212e3f"
background_2 = "#29394f"
background_3 = "#39506d"
background_4 = "#4a5e79"
background_5 = "#5a6b84"

foreground_h = "#e5e5e5"
foreground_0 = "#cdcecf"
foreground_1 = "#aeafb0"
foreground_2 = "#9d9e9f"
foreground_3 = "#8c8d8d"
foreground_4 = "#7b7c7d"
